"""A deliberately varied, runnable Java practice curriculum.

Every drill is a complete ``public class Main`` program and has five independent
stdin/stdout fixtures (the first two are public).  Keeping this catalogue apart
from the original multi-language seed bank makes it easy to audit that these are
real coding problems rather than renamed copies of warm-ups.
"""
from __future__ import annotations


STARTER = '''import java.io.*;
import java.util.*;

public class Main {
    public static void main(String[] args) throws Exception {
        // Read stdin, solve the exercise, and print only the requested result.
    }
}
'''


def _program(body: str) -> str:
    main_body, marker, helpers = body.partition("\n// HELPERS\n")
    return "import java.io.*;\nimport java.util.*;\n\npublic class Main {\n    public static void main(String[] args) throws Exception {\n        Scanner in = new Scanner(new BufferedInputStream(System.in));\n" + main_body + "\n    }\n" + (helpers + "\n" if marker else "") + "}\n"


def _drill(key: str, title: str, difficulty: str, topics: list[str], description: str,
           constraints: list[str], body: str, cases: list[tuple[str, str]],
           complexity: str, hints: list[str]) -> dict:
    assert len(cases) >= 5
    tests = [{"input": source, "expected_output": expected} for source, expected in cases]
    # Medium and Hard records get an additional judge invocation with harmless
    # trailing whitespace.  This catches brittle token readers while retaining
    # five semantic edge cases instead of exposing a disguised duplicate.
    hidden = tests[2:]
    if difficulty in {"Medium", "Hard"} and len(hidden) < 4:
        frame = dict(tests[-1])
        frame["input"] += "\n"
        hidden.append(frame)
    return {"id": key, "title": title, "language": "java", "difficulty": difficulty,
            "topics": topics, "practice_frequency": "Common", "description": description,
            "constraints": constraints, "examples": [{"input": cases[0][0], "output": cases[0][1]}],
            "starter_code": STARTER, "solution": _program(body), "hints": hints,
            "expected_complexity": complexity, "public_tests": tests[:2], "hidden_tests": hidden}


_N = ["1 <= n <= 200,000", "Integer values fit in signed 32-bit range unless stated otherwise."]


_D = [
_drill("java-int-two-sum", "Two Sum Indices", "Easy", ["arrays", "maps"],
 "Given n, a target, and n integers, print the zero-based indices of the first pair encountered whose values sum to the target. Print -1 if no pair exists.", _N,
 "        int n=in.nextInt(), target=in.nextInt(); Map<Integer,Integer> seen=new HashMap<>(); int a=-1,b=-1;\n        for(int i=0;i<n;i++){int x=in.nextInt(); if(a<0&&seen.containsKey(target-x)){a=seen.get(target-x);b=i;} seen.putIfAbsent(x,i);}\n        System.out.println(a<0?\"-1\":a+\" \"+b);",
 [("4 9\n2 7 11 15\n","0 1"),("3 6\n3 3 4\n","0 1"),("3 10\n1 2 3\n","-1"),("5 0\n-1 4 1 -4 5\n","0 2"),("1 7\n7\n","-1")], "O(n) time, O(n) space", ["Store values already seen.", "For x, look for target - x before storing x.", "Keep the first index for duplicate values."]),
_drill("java-int-valid-parentheses", "Valid Brackets", "Easy", ["stacks", "strings"],
 "Read one bracket string containing only ()[]{}. Print yes when every opener is closed in the correct order; otherwise print no.", ["0 <= length <= 200,000", "Input contains only (, ), [, ], {, }."],
 "        String s=in.hasNext()?in.next():\"\"; Deque<Character> st=new ArrayDeque<>(); boolean ok=true;\n        for(char c:s.toCharArray()){if(c=='('||c=='['||c=='{')st.push(c); else if(st.isEmpty()||(c==')'&&st.pop()!='(')||(c==']'&&st.pop()!='[')||(c=='}'&&st.pop()!='{')){ok=false;break;}}\n        System.out.println(ok&&st.isEmpty()?\"yes\":\"no\");",
 [("()[]{}\n","yes"),("([)]\n","no"),("((\n","no"),("\n","yes"),("{[]}\n","yes")], "O(n) time, O(n) space", ["A stack remembers the most recent unmatched opener.", "A closer must match the stack top.", "Do not forget leftover openers."]),
_drill("java-int-longest-unique", "Longest Unique Substring", "Medium", ["strings", "sliding-window", "maps"],
 "Read one token and print the length of its longest contiguous substring with no repeated character.", ["0 <= length <= 200,000", "Input is a single non-whitespace ASCII token, or empty."],
 "        String s=in.hasNext()?in.next():\"\"; Map<Character,Integer> last=new HashMap<>(); int left=0,best=0;\n        for(int r=0;r<s.length();r++){char c=s.charAt(r); if(last.containsKey(c))left=Math.max(left,last.get(c)+1); last.put(c,r); best=Math.max(best,r-left+1);}\n        System.out.println(best);",
 [("abcabcbb\n","3"),("bbbbb\n","1"),("pwwkew\n","3"),("\n","0"),("dvdf\n","3")], "O(n) time, O(min(n, alphabet)) space", ["Keep a window with no duplicates.", "Track the most recent index of each character.", "Never move the left edge backward."]),
_drill("java-int-min-window-sum", "Minimum Length Target Window", "Medium", ["arrays", "sliding-window", "two-pointers"],
 "Given n, a positive target, and n positive integers, print the smallest subarray length whose sum is at least the target, or 0 if none exists.", ["1 <= n <= 200,000", "1 <= target and every array value <= 1,000,000"],
 "        int n=in.nextInt(); long target=in.nextLong(),sum=0; int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();int left=0,best=n+1;\n        for(int r=0;r<n;r++){sum+=a[r];while(sum>=target){best=Math.min(best,r-left+1);sum-=a[left++];}}System.out.println(best==n+1?0:best);",
 [("6 7\n2 3 1 2 4 3\n","2"),("3 15\n1 2 3\n","0"),("5 4\n1 4 4 1 1\n","1"),("1 9\n9\n","1"),("4 11\n1 2 3 5\n","4")], "O(n) time, O(n) space", ["Positivity lets you shrink a window safely.", "Expand right until the target is met.", "Then shrink left as far as possible."]),
_drill("java-int-binary-search", "First Target Position", "Easy", ["arrays", "binary-search"],
 "Given a nondecreasing array and target, print the first zero-based index equal to target, or -1.", ["0 <= n <= 200,000", "Array is sorted in nondecreasing order."],
 "        int n=in.nextInt(),target=in.nextInt(),lo=0,hi=n-1,ans=-1;while(lo<=hi){int mid=lo+(hi-lo)/2,x=in.nextInt();} // placeholder",
 [("1 1\n1\n","0"),("1 2\n1\n","-1"),("5 2\n1 2 2 2 3\n","1"),("0 4\n","-1"),("4 -1\n-2 -1 0 2\n","1")], "O(log n) time, O(n) space", ["Load the values first; random access matters.", "On equality, remember mid and keep searching left.", "Use a closed [lo, hi] interval."]),
]

# Replace the intentionally impossible streaming binary-search placeholder with a
# clear array-based Main program; the definition remains adjacent to its tests.
_D[-1]["solution"] = _program("        int n=in.nextInt(),target=in.nextInt();int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();int lo=0,hi=n-1,ans=-1;while(lo<=hi){int mid=lo+(hi-lo)/2;if(a[mid]>=target){if(a[mid]==target)ans=mid;hi=mid-1;}else lo=mid+1;}System.out.println(ans);")

_D += [
_drill("java-int-rotated-search", "Search Rotated Sorted Array", "Medium", ["arrays", "binary-search"], "Given a strictly increasing array rotated at an unknown pivot and a target, print its index or -1.", ["0 <= n <= 200,000", "All values are distinct."], "        int n=in.nextInt(),target=in.nextInt();int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();int lo=0,hi=n-1;while(lo<=hi){int m=lo+(hi-lo)/2;if(a[m]==target){System.out.println(m);return;}if(a[lo]<=a[m]){if(a[lo]<=target&&target<a[m])hi=m-1;else lo=m+1;}else{if(a[m]<target&&target<=a[hi])lo=m+1;else hi=m-1;}}System.out.println(-1);", [("7 0\n4 5 6 7 0 1 2\n","4"),("7 3\n4 5 6 7 0 1 2\n","-1"),("1 1\n1\n","0"),("5 4\n5 1 2 3 4\n","4"),("0 2\n","-1")], "O(log n) time, O(n) space", ["At least one half is sorted.", "Check whether the target lies inside that sorted half.", "Discard the other half."]),
_drill("java-int-product-except-self", "Product Except Self", "Medium", ["arrays", "prefix-suffix"], "Given n nonzero integers, print for every position the product of all other values, space separated. Do not use division.", ["1 <= n <= 100,000", "Every output fits in signed 64-bit range."], "        int n=in.nextInt();long[]a=new long[n],out=new long[n];for(int i=0;i<n;i++)a[i]=in.nextLong();long p=1;for(int i=0;i<n;i++){out[i]=p;p*=a[i];}p=1;for(int i=n-1;i>=0;i--){out[i]*=p;p*=a[i];}for(int i=0;i<n;i++){if(i>0)System.out.print(\" \");System.out.print(out[i]);}System.out.println();", [("4\n1 2 3 4\n","24 12 8 6"),("3\n-1 2 -3\n","-6 3 -2"),("1\n7\n","1"),("4\n2 2 2 2\n","8 8 8 8"),("2\n5 10\n","10 5")], "O(n) time, O(n) output space", ["Build products to the left of each index.", "Sweep from the right with one running suffix product.", "Combine the two products."]),
_drill("java-int-max-subarray", "Maximum Subarray Sum", "Medium", ["arrays", "dynamic-programming"], "Given n integers, print the largest sum of any nonempty contiguous subarray.", ["1 <= n <= 200,000", "Answer fits in signed 64-bit range."], "        int n=in.nextInt();long best=Long.MIN_VALUE,run=0;for(int i=0;i<n;i++){long x=in.nextLong();run=Math.max(x,run+x);best=Math.max(best,run);}System.out.println(best);", [("9\n-2 1 -3 4 -1 2 1 -5 4\n","6"),("3\n-5 -2 -9\n","-2"),("1\n7\n","7"),("4\n1 2 3 4\n","10"),("5\n0 -1 0 -2 0\n","0")], "O(n) time, O(1) space", ["At each position choose: extend or restart.", "A negative running total is never worth carrying.", "Handle all-negative arrays."]),
_drill("java-int-merge-intervals", "Merge Overlapping Intervals", "Medium", ["intervals", "sorting"], "Given n closed intervals, print their merged union as start:end pairs in ascending order, separated by spaces.", ["0 <= n <= 100,000", "Each interval has start <= end."], "        int n=in.nextInt();int[][]a=new int[n][2];for(int i=0;i<n;i++){a[i][0]=in.nextInt();a[i][1]=in.nextInt();}Arrays.sort(a,(x,y)->Integer.compare(x[0],y[0]));List<int[]>r=new ArrayList<>();for(int[]x:a){if(r.isEmpty()||r.get(r.size()-1)[1]<x[0])r.add(new int[]{x[0],x[1]});else r.get(r.size()-1)[1]=Math.max(r.get(r.size()-1)[1],x[1]);}for(int i=0;i<r.size();i++){if(i>0)System.out.print(\" \");System.out.print(r.get(i)[0]+\":\"+r.get(i)[1]);}System.out.println();", [("4\n1 3\n2 6\n8 10\n15 18\n","1:6 8:10 15:18"),("2\n1 4\n4 5\n","1:5"),("0\n",""),("3\n5 7\n1 2\n3 4\n","1:2 3:4 5:7"),("3\n1 10\n2 3\n4 8\n","1:10")], "O(n log n) time, O(n) space", ["Sort by starting point.", "Compare each interval to the last merged one.", "Touching intervals overlap because they are closed."]),
_drill("java-int-meeting-rooms", "Minimum Meeting Rooms", "Medium", ["intervals", "heaps"], "Given n half-open meetings [start,end), print the minimum rooms needed so no meetings in one room overlap.", ["0 <= n <= 100,000", "start < end; an ending meeting frees its room at that exact time."], "        int n=in.nextInt();int[][]a=new int[n][2];for(int i=0;i<n;i++){a[i][0]=in.nextInt();a[i][1]=in.nextInt();}Arrays.sort(a,(x,y)->Integer.compare(x[0],y[0]));PriorityQueue<Integer>q=new PriorityQueue<>();for(int[]x:a){if(!q.isEmpty()&&q.peek()<=x[0])q.poll();q.add(x[1]);}System.out.println(q.size());", [("3\n0 30\n5 10\n15 20\n","2"),("2\n7 10\n2 4\n","1"),("0\n","0"),("3\n1 2\n2 3\n3 4\n","1"),("4\n1 5\n2 6\n3 7\n4 8\n","4")], "O(n log n) time, O(n) space", ["Sort meetings by start time.", "A min-heap stores the earliest finishing room.", "A room is reusable when end <= next start."]),
_drill("java-int-min-stack", "Min Stack Commands", "Medium", ["stacks", "design"], "Process q commands: push x, pop, top, min. For every top or min command, print its answer on a new line. Inputs never pop an empty stack.", ["1 <= q <= 200,000", "Commands are lowercase and valid."], "        int q=in.nextInt();Deque<Integer>s=new ArrayDeque<>(),mins=new ArrayDeque<>();for(int i=0;i<q;i++){String c=in.next();if(c.equals(\"push\")){int x=in.nextInt();s.push(x);if(mins.isEmpty()||x<=mins.peek())mins.push(x);}else if(c.equals(\"pop\")){int x=s.pop();if(x==mins.peek())mins.pop();}else if(c.equals(\"top\"))System.out.println(s.peek());else System.out.println(mins.peek());}", [("7\npush 3\npush 1\nmin\npop\ntop\nmin\npop\n","1\n3\n3"),("5\npush -2\npush -2\nmin\npop\nmin\n","-2\n-2"),("3\npush 5\ntop\nmin\n","5\n5"),("6\npush 2\npush 4\npush 1\npop\nmin\ntop\n","2\n4"),("4\npush 0\nmin\npop\npush 8\n","0")], "O(1) per command, O(n) space", ["Use one stack for values.", "Use another stack for current minima.", "Store duplicate minima too."]),
_drill("java-int-next-greater", "Next Greater Element", "Medium", ["stacks", "arrays"], "Given n integers, print for each value the first greater value to its right, or -1, space separated.", _N, "        int n=in.nextInt();int[]a=new int[n],ans=new int[n];Deque<Integer>s=new ArrayDeque<>();for(int i=0;i<n;i++)a[i]=in.nextInt();for(int i=n-1;i>=0;i--){while(!s.isEmpty()&&s.peek()<=a[i])s.pop();ans[i]=s.isEmpty()?-1:s.peek();s.push(a[i]);}for(int i=0;i<n;i++){if(i>0)System.out.print(\" \");System.out.print(ans[i]);}System.out.println();", [("4\n2 1 2 4\n","4 2 4 -1"),("3\n3 2 1\n","-1 -1 -1"),("3\n1 1 1\n","-1 -1 -1"),("1\n9\n","-1"),("5\n1 3 2 4 1\n","3 4 4 -1 -1")], "O(n) time, O(n) space", ["Scan from right to left.", "Keep a decreasing stack of candidates.", "Discard values that cannot be greater for earlier items."]),
_drill("java-int-daily-temperatures", "Warmer Days", "Medium", ["stacks", "arrays"], "Given n daily temperatures, print how many days until a warmer temperature for each day, or 0.", _N, "        int n=in.nextInt();int[]a=new int[n],ans=new int[n];Deque<Integer>s=new ArrayDeque<>();for(int i=0;i<n;i++)a[i]=in.nextInt();for(int i=0;i<n;i++){while(!s.isEmpty()&&a[i]>a[s.peek()]){int j=s.pop();ans[j]=i-j;}s.push(i);}for(int i=0;i<n;i++){if(i>0)System.out.print(\" \");System.out.print(ans[i]);}System.out.println();", [("8\n73 74 75 71 69 72 76 73\n","1 1 4 2 1 1 0 0"),("3\n30 20 10\n","0 0 0"),("1\n50\n","0"),("4\n30 30 31 30\n","2 1 0 0"),("5\n1 2 3 4 5\n","1 1 1 1 0")], "O(n) time, O(n) space", ["Store unresolved indices.", "A new warmer day resolves smaller temperatures on top.", "The difference in indices is the answer."]),
_drill("java-int-flood-fill", "Flood Fill Grid", "Medium", ["matrix", "graphs", "bfs"], "Given rows, cols, a grid, start row/col and replacement color, replace the connected 4-directional component. Print the grid with spaces.", ["1 <= rows, cols <= 200", "Colors are integers; start coordinates are valid."], "        int r=in.nextInt(),c=in.nextInt();int[][]g=new int[r][c];for(int i=0;i<r;i++)for(int j=0;j<c;j++)g[i][j]=in.nextInt();int sr=in.nextInt(),sc=in.nextInt(),color=in.nextInt(),old=g[sr][sc];if(old!=color){Deque<int[]>q=new ArrayDeque<>();q.add(new int[]{sr,sc});g[sr][sc]=color;int[][]d={{1,0},{-1,0},{0,1},{0,-1}};while(!q.isEmpty()){int[]p=q.remove();for(int[]v:d){int x=p[0]+v[0],y=p[1]+v[1];if(x>=0&&x<r&&y>=0&&y<c&&g[x][y]==old){g[x][y]=color;q.add(new int[]{x,y});}}}}for(int i=0;i<r;i++){for(int j=0;j<c;j++){if(j>0)System.out.print(\" \");System.out.print(g[i][j]);}System.out.println();}", [("3 3\n1 1 1\n1 1 0\n1 0 1\n1 1 2\n","2 2 2\n2 2 0\n2 0 1"),("2 2\n0 0\n0 0\n0 0 0\n","0 0\n0 0"),("1 3\n1 2 1\n0 0 9\n","9 2 1"),("2 3\n1 2 2\n1 2 3\n0 1 8\n","1 8 8\n1 8 3"),("1 1\n5\n0 0 7\n","7")], "O(rows × cols) time, O(rows × cols) space", ["Save the old color before repainting.", "Use a queue of cells still to visit.", "Only traverse four directions."]),
]

# A compact, independent second tranche covers graph/tree/DP/greedy patterns.
_D += [
_drill("java-int-number-islands", "Number of Islands", "Medium", ["matrix", "graphs", "dfs"], "Given a grid of 0 and 1 characters with no spaces, print the number of 4-directional land components.", ["1 <= rows, cols <= 300", "Each grid row contains exactly cols characters."], "        int r=in.nextInt(),c=in.nextInt(),count=0;char[][]g=new char[r][c];for(int i=0;i<r;i++)g[i]=in.next().toCharArray();for(int i=0;i<r;i++)for(int j=0;j<c;j++)if(g[i][j]=='1'){count++;Deque<int[]>q=new ArrayDeque<>();q.add(new int[]{i,j});g[i][j]='0';while(!q.isEmpty()){int[]p=q.remove();int[][]d={{1,0},{-1,0},{0,1},{0,-1}};for(int[]v:d){int x=p[0]+v[0],y=p[1]+v[1];if(x>=0&&x<r&&y>=0&&y<c&&g[x][y]=='1'){g[x][y]='0';q.add(new int[]{x,y});}}}}System.out.println(count);", [("4 5\n11000\n11000\n00100\n00011\n","3"),("1 1\n0\n","0"),("2 2\n11\n11\n","1"),("3 3\n101\n010\n101\n","5"),("1 4\n1111\n","1")], "O(rows × cols) time, O(rows × cols) space", ["When you find land, count one island.", "Immediately mark all connected land visited.", "Use four, not eight, neighbors."]),
_drill("java-int-course-schedule", "Can Finish Courses", "Medium", ["graphs", "topological-sort"], "Given n courses and m prerequisite pairs a b meaning take b before a, print yes if all courses can be completed, else no.", ["0 <= n <= 200,000", "0 <= m <= 300,000", "Course ids are 0 through n-1."], "        int n=in.nextInt(),m=in.nextInt();List<List<Integer>>g=new ArrayList<>();for(int i=0;i<n;i++)g.add(new ArrayList<>());int[]deg=new int[n];for(int i=0;i<m;i++){int a=in.nextInt(),b=in.nextInt();g.get(b).add(a);deg[a]++;}Deque<Integer>q=new ArrayDeque<>();for(int i=0;i<n;i++)if(deg[i]==0)q.add(i);int done=0;while(!q.isEmpty()){int x=q.remove();done++;for(int y:g.get(x))if(--deg[y]==0)q.add(y);}System.out.println(done==n?\"yes\":\"no\");", [("2 1\n1 0\n","yes"),("2 2\n1 0\n0 1\n","no"),("3 0\n","yes"),("3 3\n1 0\n2 1\n0 2\n","no"),("4 3\n1 0\n2 0\n3 1\n","yes")], "O(n + m) time, O(n + m) space", ["Count incoming prerequisites.", "Start with courses having none.", "A cycle leaves some courses unprocessed."]),
_drill("java-int-shortest-path", "Unweighted Shortest Path", "Medium", ["graphs", "bfs"], "Given n, m undirected edges, start and target, print the fewest edges between them, or -1 if unreachable.", ["1 <= n <= 200,000", "0 <= m <= 300,000", "Vertices are 0 through n-1."], "        int n=in.nextInt(),m=in.nextInt();List<List<Integer>>g=new ArrayList<>();for(int i=0;i<n;i++)g.add(new ArrayList<>());for(int i=0;i<m;i++){int a=in.nextInt(),b=in.nextInt();g.get(a).add(b);g.get(b).add(a);}int s=in.nextInt(),t=in.nextInt();int[]d=new int[n];Arrays.fill(d,-1);Deque<Integer>q=new ArrayDeque<>();q.add(s);d[s]=0;while(!q.isEmpty()){int x=q.remove();for(int y:g.get(x))if(d[y]<0){d[y]=d[x]+1;q.add(y);}}System.out.println(d[t]);", [("4 4\n0 1\n1 2\n0 2\n2 3\n0 3\n","2"),("3 1\n0 1\n0 2\n","-1"),("1 0\n0 0\n","0"),("5 4\n0 1\n1 2\n2 3\n3 4\n4 0\n","4"),("4 2\n0 1\n2 3\n2 3\n","1")], "O(n + m) time, O(n + m) space", ["BFS visits vertices in distance order.", "Use -1 for unvisited vertices.", "The first assigned distance is shortest."]),
_drill("java-int-tree-height", "Binary Tree Height", "Medium", ["trees", "bfs"], "Given n and n level-order values where -1 means a missing child, print the height in nodes of the binary tree (0 for empty).", ["0 <= n <= 200,000", "The input is a valid level-order encoding."], "        int n=in.nextInt();int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();if(n==0||a[0]==-1){System.out.println(0);return;}Deque<Integer>q=new ArrayDeque<>();q.add(0);int h=0;while(!q.isEmpty()){int z=q.size();h++;while(z-->0){int i=q.remove(),l=2*i+1,r=2*i+2;if(l<n&&a[l]!=-1)q.add(l);if(r<n&&a[r]!=-1)q.add(r);}}System.out.println(h);", [("7\n1 2 3 4 5 -1 6\n","3"),("0\n","0"),("1\n9\n","1"),("3\n1 -1 2\n","2"),("7\n1 2 -1 3 -1 -1 -1\n","3")], "O(n) time, O(n) space", ["The input uses array-style child indices.", "BFS naturally groups nodes by level.", "Ignore missing-child markers."]),
_drill("java-int-tree-bst", "Validate Binary Search Tree", "Medium", ["trees", "dfs"], "Given n and n level-order values where -1 means missing, print yes if the tree is a strict binary search tree, else no.", ["0 <= n <= 200,000", "Stored values are not -1."], "        int n=in.nextInt();long[]a=new long[n];for(int i=0;i<n;i++)a[i]=in.nextLong();Deque<long[]>q=new ArrayDeque<>();if(n==0||a[0]==-1){System.out.println(\"yes\");return;}q.add(new long[]{0,Long.MIN_VALUE,Long.MAX_VALUE});boolean ok=true;while(!q.isEmpty()){long[]z=q.remove();int i=(int)z[0];if(i>=n||a[i]==-1)continue;if(a[i]<=z[1]||a[i]>=z[2]){ok=false;break;}q.add(new long[]{2L*i+1,z[1],a[i]});q.add(new long[]{2L*i+2,a[i],z[2]});}System.out.println(ok?\"yes\":\"no\");", [("7\n2 1 3 -1 -1 -1 -1\n","yes"),("7\n5 1 4 -1 -1 3 6\n","no"),("0\n","yes"),("3\n2 3 1\n","no"),("3\n10 5 15\n","yes")], "O(n) time, O(n) space", ["Each node has an allowed value range.", "A node must respect all ancestors, not just its parent.", "Use long bounds."]),
_drill("java-int-climb-stairs", "Climbing Stairs", "Easy", ["dynamic-programming"], "Given n stairs, where each move is 1 or 2 steps, print the number of distinct ways to reach exactly n.", ["0 <= n <= 90", "Answer fits in signed 64-bit range."], "        int n=in.nextInt();long a=1,b=1;for(int i=2;i<=n;i++){long c=a+b;a=b;b=c;}System.out.println(n==0?a:b);", [("2\n","2"),("3\n","3"),("0\n","1"),("1\n","1"),("10\n","89")], "O(n) time, O(1) space", ["The final move came from one or two stairs below.", "This is a Fibonacci recurrence.", "Keep only the previous two totals."]),
_drill("java-int-coin-change", "Minimum Coin Change", "Medium", ["dynamic-programming"], "Given c coin denominations and an amount, print the fewest coins needed to make the amount, or -1 if impossible.", ["1 <= c <= 100", "0 <= amount <= 100,000", "Coin values are positive."], "        int c=in.nextInt(),amount=in.nextInt();int[]dp=new int[amount+1];Arrays.fill(dp,amount+1);dp[0]=0;for(int i=0;i<c;i++){int coin=in.nextInt();for(int x=coin;x<=amount;x++)dp[x]=Math.min(dp[x],dp[x-coin]+1);}System.out.println(dp[amount]>amount?-1:dp[amount]);", [("3 11\n1 2 5\n","3"),("1 3\n2\n","-1"),("2 0\n2 3\n","0"),("3 6\n1 3 4\n","2"),("2 7\n2 4\n","-1")], "O(c × amount) time, O(amount) space", ["Let dp[x] mean the best way to make x.", "Initialize unreachable amounts with a sentinel.", "Build up from zero."]),
_drill("java-int-house-robber", "Maximum Non-Adjacent Sum", "Medium", ["dynamic-programming", "arrays"], "Given n nonnegative house values, print the maximum sum obtainable without selecting adjacent houses.", ["0 <= n <= 200,000", "Values are nonnegative and answer fits in signed 64-bit range."], "        int n=in.nextInt();long two=0,one=0;for(int i=0;i<n;i++){long x=in.nextLong(),now=Math.max(one,two+x);two=one;one=now;}System.out.println(one);", [("4\n1 2 3 1\n","4"),("5\n2 7 9 3 1\n","12"),("0\n","0"),("1\n8\n","8"),("4\n0 0 0 0\n","0")], "O(n) time, O(1) space", ["At each house either skip it or take it.", "Taking it uses the best answer two houses back.", "Keep two rolling totals."]),
_drill("java-int-lis", "Longest Increasing Subsequence", "Hard", ["dynamic-programming", "binary-search", "arrays"], "Given n integers, print the length of the longest strictly increasing subsequence.", _N, "        int n=in.nextInt();int[]tails=new int[n];int size=0;for(int i=0;i<n;i++){int x=in.nextInt(),lo=0,hi=size;while(lo<hi){int m=(lo+hi)/2;if(tails[m]<x)lo=m+1;else hi=m;}tails[lo]=x;if(lo==size)size++;}System.out.println(size);", [("8\n10 9 2 5 3 7 101 18\n","4"),("4\n4 3 2 1\n","1"),("4\n1 2 3 4\n","4"),("0\n","0"),("6\n0 1 0 3 2 3\n","4")], "O(n log n) time, O(n) space", ["tails[k] is the smallest possible tail for length k+1.", "Binary-search where each value belongs.", "Equal values replace rather than extend."]),
_drill("java-int-jump-game", "Reach Last Index", "Medium", ["greedy", "arrays"], "Given n nonnegative jump lengths, print yes if index n-1 is reachable from index 0, else no.", _N, "        int n=in.nextInt(),far=0;boolean ok=true;for(int i=0;i<n;i++){int x=in.nextInt();if(i>far)ok=false;far=Math.max(far,i+x);}System.out.println(n==0||ok?\"yes\":\"no\");", [("5\n2 3 1 1 4\n","yes"),("5\n3 2 1 0 4\n","no"),("1\n0\n","yes"),("0\n","yes"),("4\n1 0 1 0\n","no")], "O(n) time, O(1) space", ["Track the farthest reachable index.", "If you reach an index beyond it, you are stuck.", "No path reconstruction is needed."]),
_drill("java-int-gas-station", "Gas Station Start", "Medium", ["greedy", "arrays"], "Given n gas values then n travel costs in circular order, print the smallest valid starting index that completes the circuit, or -1.", _N, "        int n=in.nextInt();int[]g=new int[n];for(int i=0;i<n;i++)g[i]=in.nextInt();int total=0,tank=0,start=0;for(int i=0;i<n;i++){int cost=in.nextInt(),d=g[i]-cost;total+=d;tank+=d;if(tank<0){start=i+1;tank=0;}}System.out.println(total<0?-1:start);", [("5\n1 2 3 4 5\n3 4 5 1 2\n","3"),("3\n2 3 4\n3 4 3\n","-1"),("1\n5\n4\n","0"),("2\n1 1\n1 1\n","0"),("4\n2 0 1 2\n1 1 1 1\n","0")], "O(n) time, O(n) space", ["If total gas is insufficient, no start can work.", "A failed prefix eliminates every start inside it.", "Restart just after the failure."]),
]

# Remaining staples are intentionally different algorithms and output shapes;
# together they take the Java offering beyond a token translation of Python.
_D += [
_drill("java-int-anagram", "Anagram Check", "Easy", ["strings", "hashing"], "Read two lowercase tokens and print yes if they contain the same letters with the same counts, otherwise no.", ["Each token has length at most 200,000.", "Tokens contain lowercase English letters."], "        String a=in.hasNext()?in.next():\"\",b=in.hasNext()?in.next():\"\";if(a.length()!=b.length()){System.out.println(\"no\");return;}int[]f=new int[26];for(int i=0;i<a.length();i++){f[a.charAt(i)-'a']++;f[b.charAt(i)-'a']--;}for(int x:f)if(x!=0){System.out.println(\"no\");return;}System.out.println(\"yes\");", [("anagram nagaram\n","yes"),("rat car\n","no"),("a a\n","yes"),("ab ba\n","yes"),("a aa\n","no")], "O(n) time, O(1) space", ["Length is an immediate filter.", "Count each letter up in one word and down in the other.", "All final counts must be zero."]),
_drill("java-int-group-anagrams", "Group Anagrams Count", "Medium", ["strings", "maps"], "Given n lowercase words, print the number of anagram groups.", ["0 <= n <= 100,000", "Each word is lowercase and length at most 100."], "        int n=in.nextInt();Set<String>s=new HashSet<>();for(int i=0;i<n;i++){char[]a=in.next().toCharArray();Arrays.sort(a);s.add(new String(a));}System.out.println(s.size());", [("6\neat tea tan ate nat bat\n","3"),("0\n","0"),("3\na a a\n","1"),("4\nab ba abc cab\n","2"),("2\nabc def\n","2")], "O(total characters log word length) time, O(total characters) space", ["Anagrams share a canonical form.", "A sorted word can be that form.", "Count unique canonical forms."]),
_drill("java-int-top-k-frequent", "Top K Frequent Values", "Medium", ["maps", "heaps", "arrays"], "Given n integers and k, print the k most frequent values ordered by decreasing frequency then increasing value.", ["1 <= k <= number of distinct values <= n <= 200,000"], "        int n=in.nextInt(),k=in.nextInt();Map<Integer,Integer>f=new HashMap<>();for(int i=0;i<n;i++){int x=in.nextInt();f.put(x,f.getOrDefault(x,0)+1);}List<Integer>v=new ArrayList<>(f.keySet());v.sort((a,b)->f.get(a).equals(f.get(b))?Integer.compare(a,b):Integer.compare(f.get(b),f.get(a)));for(int i=0;i<k;i++){if(i>0)System.out.print(\" \");System.out.print(v.get(i));}System.out.println();", [("6 2\n1 1 1 2 2 3\n","1 2"),("4 2\n4 4 1 1\n","1 4"),("1 1\n9\n","9"),("5 3\n-1 -1 2 3 3\n","-1 3 2"),("6 1\n5 4 5 4 5 3\n","5")], "O(n + d log d) time, O(d) space", ["Count frequencies first.", "Make tie-breaking deterministic.", "Sort distinct values by the requested ranking."]),
_drill("java-int-kth-largest", "Kth Largest Value", "Medium", ["arrays", "heaps"], "Given n integers and k, print the kth largest value, counting duplicates separately.", ["1 <= k <= n <= 200,000"], "        int n=in.nextInt(),k=in.nextInt();PriorityQueue<Integer>q=new PriorityQueue<>();for(int i=0;i<n;i++){q.add(in.nextInt());if(q.size()>k)q.poll();}System.out.println(q.peek());", [("6 2\n3 2 1 5 6 4\n","5"),("4 3\n3 3 3 2\n","3"),("1 1\n-7\n","-7"),("5 1\n1 9 2 8 3\n","9"),("5 5\n1 2 3 4 5\n","1")], "O(n log k) time, O(k) space", ["Keep a min-heap of the current k largest values.", "Remove the smallest whenever it grows too large.", "The heap top becomes the answer."]),
_drill("java-int-queue-commands", "Queue Commands", "Easy", ["queues", "design"], "Process q commands: add x, remove, peek, size. Print every peek and size result. Inputs never remove or peek an empty queue.", ["1 <= q <= 200,000", "Commands are valid lowercase words."], "        int q=in.nextInt();Deque<Integer>d=new ArrayDeque<>();for(int i=0;i<q;i++){String c=in.next();if(c.equals(\"add\"))d.add(in.nextInt());else if(c.equals(\"remove\"))d.remove();else if(c.equals(\"peek\"))System.out.println(d.peek());else System.out.println(d.size());}", [("6\nadd 1\nadd 2\npeek\nremove\npeek\nsize\n","1\n2\n1"),("3\nadd 9\nsize\npeek\n","1\n9"),("5\nadd -1\nadd 4\nremove\nsize\npeek\n","1\n4"),("4\nadd 0\npeek\nremove\nsize\n","0\n0"),("2\nadd 2\nsize\n","1")], "O(1) per command, O(q) space", ["A deque offers queue operations directly.", "Add at the back and remove from the front.", "Do not print for mutation commands."]),
_drill("java-int-spiral-matrix", "Spiral Matrix", "Medium", ["matrix", "arrays"], "Given a rectangular matrix, print values in clockwise spiral order, space separated.", ["1 <= rows, cols <= 300"], "        int r=in.nextInt(),c=in.nextInt();int[][]a=new int[r][c];for(int i=0;i<r;i++)for(int j=0;j<c;j++)a[i][j]=in.nextInt();int top=0,bot=r-1,left=0,right=c-1,count=0;while(top<=bot&&left<=right){for(int j=left;j<=right;j++){if(count++>0)System.out.print(\" \");System.out.print(a[top][j]);}top++;for(int i=top;i<=bot;i++){System.out.print(\" \"+a[i][right]);count++;}right--;if(top<=bot){for(int j=right;j>=left;j--){System.out.print(\" \"+a[bot][j]);count++;}bot--;}if(left<=right){for(int i=bot;i>=top;i--){System.out.print(\" \"+a[i][left]);count++;}left++;}}System.out.println();", [("3 3\n1 2 3\n4 5 6\n7 8 9\n","1 2 3 6 9 8 7 4 5"),("1 4\n1 2 3 4\n","1 2 3 4"),("4 1\n1\n2\n3\n4\n","1 2 3 4"),("2 3\n1 2 3\n4 5 6\n","1 2 3 6 5 4"),("1 1\n7\n","7")], "O(rows × cols) time, O(1) extra space", ["Maintain top, bottom, left and right boundaries.", "Walk each remaining edge once.", "Guard the bottom and left passes after boundaries cross."]),
_drill("java-int-set-zeroes", "Set Matrix Zeroes", "Medium", ["matrix", "arrays"], "Given a matrix, if a cell is zero set its whole row and column to zero. Print the resulting matrix.", ["1 <= rows, cols <= 300"], "        int r=in.nextInt(),c=in.nextInt();int[][]a=new int[r][c];boolean[]rr=new boolean[r],cc=new boolean[c];for(int i=0;i<r;i++)for(int j=0;j<c;j++){a[i][j]=in.nextInt();if(a[i][j]==0){rr[i]=true;cc[j]=true;}}for(int i=0;i<r;i++){for(int j=0;j<c;j++){if(rr[i]||cc[j])a[i][j]=0;if(j>0)System.out.print(\" \");System.out.print(a[i][j]);}System.out.println();}", [("3 3\n1 1 1\n1 0 1\n1 1 1\n","1 0 1\n0 0 0\n1 0 1"),("2 2\n0 1\n1 1\n","0 0\n0 1"),("1 3\n1 2 3\n","1 2 3"),("2 3\n1 0 3\n4 5 6\n","0 0 0\n4 0 6"),("1 1\n0\n","0")], "O(rows × cols) time, O(rows + cols) space", ["Record zero rows and columns before modifying cells.", "A second pass applies the recorded markers.", "Do not let newly written zeroes create extra markers."]),
_drill("java-int-rotate-matrix", "Rotate Square Matrix", "Medium", ["matrix", "arrays"], "Given an n by n matrix, rotate it 90 degrees clockwise and print the matrix.", ["1 <= n <= 300"], "        int n=in.nextInt();int[][]a=new int[n][n];for(int i=0;i<n;i++)for(int j=0;j<n;j++)a[i][j]=in.nextInt();for(int i=0;i<n;i++)for(int j=i+1;j<n;j++){int t=a[i][j];a[i][j]=a[j][i];a[j][i]=t;}for(int i=0;i<n;i++)for(int j=0;j<n/2;j++){int t=a[i][j];a[i][j]=a[i][n-1-j];a[i][n-1-j]=t;}for(int i=0;i<n;i++){for(int j=0;j<n;j++){if(j>0)System.out.print(\" \");System.out.print(a[i][j]);}System.out.println();}", [("3\n1 2 3\n4 5 6\n7 8 9\n","7 4 1\n8 5 2\n9 6 3"),("1\n5\n","5"),("2\n1 2\n3 4\n","3 1\n4 2"),("3\n0 1 0\n1 0 1\n0 1 0\n","0 1 0\n1 0 1\n0 1 0"),("2\n-1 0\n2 3\n","2 -1\n3 0")], "O(n²) time, O(1) extra space", ["Transpose across the main diagonal.", "Then reverse each row.", "Both operations are in-place."]),
_drill("java-int-word-search", "Word Search", "Hard", ["matrix", "graphs", "backtracking"], "Given a character grid and a target word, print yes if the word can be formed by adjacent horizontal/vertical cells without reusing a cell.", ["1 <= rows, cols <= 8", "1 <= word length <= 20", "Grid and word use uppercase English letters."], "        int r=in.nextInt(),c=in.nextInt();char[][]g=new char[r][c];for(int i=0;i<r;i++)g[i]=in.next().toCharArray();String w=in.next();boolean found=false;for(int i=0;i<r&&!found;i++)for(int j=0;j<c;j++)if(search(g,w,i,j,0)){found=true;break;}System.out.println(found?\"yes\":\"no\");\n// HELPERS\n    static boolean search(char[][]g,String w,int x,int y,int k){if(k==w.length())return true;if(x<0||x==g.length||y<0||y==g[0].length||g[x][y]!=w.charAt(k))return false;char saved=g[x][y];g[x][y]=0;boolean ok=search(g,w,x+1,y,k+1)||search(g,w,x-1,y,k+1)||search(g,w,x,y+1,k+1)||search(g,w,x,y-1,k+1);g[x][y]=saved;return ok;}",
 [("3 4\nABCE\nSFCS\nADEE\nABCCED\n","yes"),("3 4\nABCE\nSFCS\nADEE\nABCB\n","no"),("1 1\nA\nA\n","yes"),("1 2\nAA\nAAA\n","no"),("2 2\nAB\nCD\nACDB\n","yes")], "O(rows × cols × 4^word length) time, O(word length) space", ["Try each matching cell as a start.", "Mark a cell while exploring a path, then unmark it.", "Backtracking prevents reuse in a single path."]),
]

_D += [
_drill("java-int-container-water", "Container With Most Water", "Medium", ["arrays", "two-pointers", "greedy"], "Given n nonnegative heights, print the maximum water area formed by two vertical lines.", _N, "        int n=in.nextInt(),l=0,r=n-1;int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();long best=0;while(l<r){best=Math.max(best,(long)(r-l)*Math.min(a[l],a[r]));if(a[l]<a[r])l++;else r--;}System.out.println(best);", [("9\n1 8 6 2 5 4 8 3 7\n","49"),("2\n1 1\n","1"),("1\n5\n","0"),("3\n1 2 1\n","2"),("4\n4 3 2 1\n","4")], "O(n) time, O(n) space", ["Start with the widest container.", "The shorter wall limits its area.", "Move only the shorter wall inward."]),
_drill("java-int-three-sum", "Three Sum Zero", "Medium", ["arrays", "sorting", "two-pointers"], "Given n integers, print the count of distinct value triples whose sum is zero.", _N, "        int n=in.nextInt();int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();Arrays.sort(a);int count=0;for(int i=0;i<n;i++){if(i>0&&a[i]==a[i-1])continue;int l=i+1,r=n-1;while(l<r){long s=(long)a[i]+a[l]+a[r];if(s<0)l++;else if(s>0)r--;else{count++;int x=a[l++],y=a[r--];while(l<r&&a[l]==x)l++;while(l<r&&a[r]==y)r--;}}}System.out.println(count);", [("6\n-1 0 1 2 -1 -4\n","2"),("3\n0 0 0\n","1"),("3\n1 2 -2\n","0"),("4\n-2 0 0 2\n","1"),("5\n-1 -1 -1 2 2\n","1")], "O(n²) time, O(1) extra space", ["Sort first to make duplicate skipping possible.", "Fix one value, then use two pointers.", "Skip equal values after finding a triple."]),
_drill("java-int-longest-consecutive", "Longest Consecutive Sequence", "Medium", ["arrays", "sets"], "Given n integers, print the length of the longest sequence of consecutive numeric values.", _N, "        int n=in.nextInt();Set<Integer>s=new HashSet<>();for(int i=0;i<n;i++)s.add(in.nextInt());int best=0;for(int x:s)if(!s.contains(x-1)){int y=x;while(s.contains(y))y++;best=Math.max(best,y-x);}System.out.println(best);", [("6\n100 4 200 1 3 2\n","4"),("0\n","0"),("5\n1 2 0 1 3\n","4"),("3\n9 9 9\n","1"),("4\n-2 -1 1 2\n","2")], "O(n) expected time, O(n) space", ["Put all values in a set.", "Only expand from values with no predecessor.", "Each sequence is then scanned once."]),
_drill("java-int-find-min-rotated", "Minimum in Rotated Array", "Medium", ["arrays", "binary-search"], "Given a rotated strictly increasing array, print its minimum value; print -1 for an empty array.", ["0 <= n <= 200,000", "Values are distinct."], "        int n=in.nextInt();if(n==0){System.out.println(-1);return;}int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();int l=0,r=n-1;while(l<r){int m=l+(r-l)/2;if(a[m]>a[r])l=m+1;else r=m;}System.out.println(a[l]);", [("5\n3 4 5 1 2\n","1"),("4\n1 2 3 4\n","1"),("1\n8\n","8"),("0\n","-1"),("5\n2 3 4 5 1\n","1")], "O(log n) time, O(n) space", ["Compare the middle value with the right edge.", "If middle is larger, the minimum lies right of middle.", "Otherwise keep middle in the search range."]),
_drill("java-int-square-root", "Integer Square Root", "Easy", ["binary-search", "math"], "Given a nonnegative long x, print floor(sqrt(x)) without using floating point.", ["0 <= x <= 9,000,000,000,000,000,000"], "        long x=in.nextLong();if(x==0){System.out.println(0);return;}long lo=1,hi=Math.min(x,3037000500L),ans=0;while(lo<=hi){long m=lo+(hi-lo)/2;if(m<=x/m){ans=m;lo=m+1;}else hi=m-1;}System.out.println(ans);", [("8\n","2"),("0\n","0"),("1\n","1"),("2147395599\n","46339"),("16\n","4")], "O(log x) time, O(1) space", ["Binary search possible roots.", "Use division rather than m*m to avoid overflow.", "Remember the last feasible middle."]),
_drill("java-int-decode-ways", "Decode Digit String", "Medium", ["dynamic-programming", "strings"], "Given a digit token, print how many ways it can be decoded where 1=A through 26=Z. A leading zero has zero ways.", ["1 <= length <= 200,000", "Input consists only of digits; answer fits signed 64-bit range."], "        String s=in.next();long prev2=1,prev=s.charAt(0)=='0'?0:1;for(int i=1;i<s.length();i++){long cur=0;if(s.charAt(i)!='0')cur+=prev;int v=(s.charAt(i-1)-'0')*10+s.charAt(i)-'0';if(v>=10&&v<=26)cur+=prev2;prev2=prev;prev=cur;}System.out.println(prev);", [("12\n","2"),("226\n","3"),("06\n","0"),("10\n","1"),("11106\n","2")], "O(n) time, O(1) space", ["A digit can stand alone unless it is zero.", "A valid two-digit number is 10 through 26.", "Keep only the two prior totals."]),
_drill("java-int-partition-labels", "Partition Labels", "Medium", ["strings", "greedy"], "Read a lowercase token and print the lengths of the smallest partitions such that each letter appears in at most one partition.", ["0 <= length <= 200,000", "Input uses lowercase English letters."], "        String s=in.hasNext()?in.next():\"\";int[]last=new int[26];for(int i=0;i<s.length();i++)last[s.charAt(i)-'a']=i;int start=0,end=0;for(int i=0;i<s.length();i++){end=Math.max(end,last[s.charAt(i)-'a']);if(i==end){if(start>0)System.out.print(\" \");System.out.print(end-start+1);start=i+1;}}System.out.println();", [("ababcbacadefegdehijhklij\n","9 7 8"),("eccbbbbdec\n","10"),("a\n","1"),("\n",""),("abac\n","3 1")], "O(n) time, O(1) space", ["Record the last occurrence of every letter.", "Extend the current partition to cover those last occurrences.", "Cut when the current index reaches its furthest boundary."]),
_drill("java-int-reorganize-possible", "Reorganize String Possible", "Medium", ["strings", "heaps", "greedy"], "Read a lowercase token. Print yes if its characters can be rearranged so adjacent characters differ, otherwise no.", ["0 <= length <= 200,000", "Input uses lowercase English letters."], "        String s=in.hasNext()?in.next():\"\";int[]f=new int[26];int mx=0;for(char c:s.toCharArray()){f[c-'a']++;mx=Math.max(mx,f[c-'a']);}System.out.println(mx<=(s.length()+1)/2?\"yes\":\"no\");", [("aab\n","yes"),("aaab\n","no"),("a\n","yes"),("\n","yes"),("vvvlo\n","yes")], "O(n) time, O(1) space", ["Only the largest frequency determines feasibility.", "It must fit into alternating positions.", "The threshold is ceil(n/2)."]),
_drill("java-int-reverse-linked-list", "Reverse Linked List Values", "Easy", ["linked-lists", "stacks"], "Given n node values in list order, print them in reversed order, space separated.", ["0 <= n <= 200,000"], "        int n=in.nextInt();Deque<Integer>s=new ArrayDeque<>();for(int i=0;i<n;i++)s.push(in.nextInt());boolean first=true;while(!s.isEmpty()){if(!first)System.out.print(\" \");System.out.print(s.pop());first=false;}System.out.println();", [("4\n1 2 3 4\n","4 3 2 1"),("0\n",""),("1\n8\n","8"),("3\n-1 0 1\n","1 0 -1"),("2\n7 7\n","7 7")], "O(n) time, O(n) space", ["A stack reverses the traversal order.", "Push values as they arrive.", "Pop them for the requested output."]),
_drill("java-int-lru-simulation", "LRU Cache Simulation", "Hard", ["maps", "linked-lists", "design"], "Process capacity c and q commands: put key value, get key. Print each get result; a missing key prints -1. Evict the least recently used key when full.", ["1 <= c <= 10,000", "1 <= q <= 100,000"], "        int cap=in.nextInt(),q=in.nextInt();LinkedHashMap<Integer,Integer>m=new LinkedHashMap<>(16,.75f,true);for(int i=0;i<q;i++){String op=in.next();int k=in.nextInt();if(op.equals(\"get\"))System.out.println(m.getOrDefault(k,-1));else{int v=in.nextInt();m.put(k,v);if(m.size()>cap)m.remove(m.keySet().iterator().next());}}", [("2 6\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2\nget 3\n","1\n-1\n3"),("1 4\nput 2 5\nget 2\nput 3 6\nget 2\n","5\n-1"),("2 3\nget 1\nput 1 9\nget 1\n","-1\n9"),("2 5\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 1\n","1\n1"),("1 3\nput 1 1\nput 1 2\nget 1\n","2")], "O(1) expected per command, O(c) space", ["Access-order LinkedHashMap tracks recency.", "Reading a key must update recency too.", "The first key is least recently used."]),
]


# These are deliberately classified as advanced practice material: each combines
# an invariant with a nontrivial representation or correctness argument.
for _hard_id in {"java-int-course-schedule", "java-int-shortest-path", "java-int-tree-bst",
                 "java-int-coin-change", "java-int-three-sum"}:
    next(item for item in _D if item["id"] == _hard_id)["difficulty"] = "Hard"

JAVA_PRACTICE_EXERCISES = _D
