"""Curated Java 17 drills 101--120; data-only on import."""
from __future__ import annotations

STARTER='''import java.io.*;\nimport java.util.*;\npublic class Main { public static void main(String[] args) throws Exception { } }\n'''
def P(b: str, h: str="") -> str:
 return f"import java.io.*;\nimport java.util.*;\npublic class Main {{ public static void main(String[] args) throws Exception {{ Scanner in=new Scanner(new BufferedInputStream(System.in));{b} }}{h}}}\n"
def C(i: str,o: str)->dict[str,str]: return {"input":i,"expected_output":o}
def D(n:int,t:str,d:str,topic:str,desc:str,con:list[str],hints:list[str],cx:str,sol:str,p:list[dict],q:list[dict])->dict:
 return {"id":f"java-curated-{n:03d}","title":t,"language":"java","difficulty":d,"topics":[topic],"curriculum_family":topic,"practice_frequency":"Common","description":desc,"constraints":con,"hints":hints,"expected_complexity":cx,"starter_code":STARTER,"solution":sol,"public_tests":p,"hidden_tests":q,"examples":[{"input":x["input"],"output":x["expected_output"]} for x in p]}

JAVA_CURRICULUM_PART3=[
D(101,"Majority Vote","Easy","arrays","Print the value occurring more than n/2 times; a majority is guaranteed.",["1 <= n <= 200000."],["Keep a candidate and vote count.","Reset only at zero votes.","The guarantee removes a verification pass."],"O(n) time, O(1) auxiliary space",P("int n=in.nextInt(),c=0,v=0;for(int i=0;i<n;i++){int x=in.nextInt();if(c==0)v=x;c+=x==v?1:-1;}System.out.println(v);"),[C("3\n2 2 1\n","2"),C("5\n3 3 4 2 3\n","3")],[C("1\n9\n","9"),C("7\n-1 -1 2 -1 3 -1 -1\n","-1"),C("4\n0 0 0 1\n","0"),C("5\n8 7 8 8 7\n","8")]),
D(102,"Missing Range Value","Easy","bitwise","The input contains n distinct values from 0 through n with one absent. Print the absent value.",["0 <= n <= 200000."],["XOR all indices 0 through n.","XOR every supplied value too.","Equal values cancel."],"O(n) time, O(1) auxiliary space",P("int n=in.nextInt(),x=n;for(int i=0;i<n;i++)x^=i^in.nextInt();System.out.println(x);"),[C("3\n3 0 1\n","2"),C("1\n0\n","1")],[C("0\n","0"),C("4\n0 1 2 3\n","4"),C("4\n1 2 3 4\n","0"),C("5\n5 2 1 0 3\n","4")]),
D(103,"Greatest Common Divisor And LCM","Medium","numbers","Print gcd then lcm of two positive long values.",["1 <= a,b <= 10^12.","The stated lcm fits in signed long."],["Euclid repeatedly takes a remainder.","Save the original gcd.","Divide before multiplying for lcm."],"O(log min(a,b)) time, O(1) auxiliary space",P("long a=in.nextLong(),b=in.nextLong(),x=a,y=b;while(y!=0){long r=x%y;x=y;y=r;}System.out.println(x+\" \"+(a/x*b));"),[C("12 18\n","6 36"),C("7 13\n","1 91")],[C("1 1\n","1 1"),C("1000000000 999999999\n","1 999999999000000000"),C("48 180\n","12 720"),C("36 60\n","12 180")]),
D(104,"Modular Power","Medium","numbers","Print base raised to exponent modulo modulus.",["0 <= exponent <= 10^18; 2 <= modulus <= 2*10^9.","0 <= base < modulus."],["Square the base after each exponent bit.","Multiply the answer only for a set bit.","Use long for products."],"O(log exponent) time, O(1) auxiliary space",P("long a=in.nextLong(),e=in.nextLong(),m=in.nextLong(),r=1%m;while(e>0){if((e&1)==1)r=r*a%m;a=a*a%m;e>>=1;}System.out.println(r);"),[C("2 10 1000\n","24"),C("5 0 7\n","1")],[C("0 4 13\n","0"),C("7 1 11\n","7"),C("2 63 1000000007\n","291172004"),C("10 3 6\n","4")]),
D(105,"Middle Linked-List Value","Medium","linked-lists","Given list values, print the second middle value for even length, or NONE for an empty list.",["0 <= n <= 200000."],["A slow pointer moves once.","A fast pointer moves twice.","When fast ends, slow is the requested middle."],"O(n) time, O(n) auxiliary space",P("int n=in.nextInt();int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();System.out.println(n==0?\"NONE\":a[n/2]);"),[C("5\n1 2 3 4 5\n","3"),C("4\n1 2 3 4\n","3")],[C("0\n","NONE"),C("1\n8\n","8"),C("2\n9 7\n","7"),C("3\n-1 0 1\n","0")]),
D(106,"Merge Sorted Sequences","Medium","linked-lists","Line 1 contains n m, followed by two nondecreasing serialized lists. Merge and print one nondecreasing sequence.",["0 <= n,m and n+m <= 1900.","The input contains exactly n then m signed 32-bit values; the bound keeps output below the local runner limit."],["Keep one index in each sequence.","Take the smaller current value.","Append whichever suffix remains."],"O(n+m) time, O(n+m) auxiliary space",P("int n=in.nextInt(),m=in.nextInt(),i=0,j=0;int[]a=new int[n],b=new int[m];for(i=0;i<n;i++)a[i]=in.nextInt();for(j=0;j<m;j++)b[j]=in.nextInt();i=0;j=0;boolean first=true;while(i<n||j<m){int x=j==m||(i<n&&a[i]<=b[j])?a[i++]:b[j++];if(!first)System.out.print(\" \");first=false;System.out.print(x);}System.out.println();"),[C("3 3\n1 2 4\n1 3 4\n","1 1 2 3 4 4"),C("0 2\n\n2 5\n","2 5")],[C("2 0\n1 3\n\n","1 3"),C("2 2\n1 1\n1 1\n","1 1 1 1"),C("1 2\n-3\n-2 0\n","-3 -2 0"),C("0 0\n\n\n","")]),
D(107,"Remove Nth Value From End","Medium","linked-lists","Line 1 contains listLength and a valid 1-based n; line 2 serializes the list. Remove the nth value from the end and print the remainder.",["1 <= n <= list length <= 1900.","Values fit signed 32-bit integers; the length bound keeps output below the local runner limit."],["A gap of n separates two pointers.","Advance both until the leading pointer ends.","The trailing pointer precedes the removed value."],"O(length) time, O(length) auxiliary space",P("int z=in.nextInt(),k=in.nextInt();int[]a=new int[z];for(int i=0;i<z;i++)a[i]=in.nextInt();int drop=z-k;for(int i=0;i<z;i++)if(i!=drop){if(i>0&&!(i==1&&drop==0))System.out.print(\" \");System.out.print(a[i]);}System.out.println();"),[C("5 2\n1 2 3 4 5\n","1 2 3 5"),C("1 1\n9\n","")],[C("2 2\n1 2\n","2"),C("2 1\n1 2\n","1"),C("3 3\n7 8 9\n","8 9"),C("4 3\n1 1 2 3\n","1 2 3")]),
D(
 108, "Cycle Entry Index", "Medium", "linked-lists",
 "Line 1 is n; line 2 has n values; line 3 has every node's next index (-1 is null); line 4 is the head index. Print the reachable cycle's entry index, or -1.",
 ["0 <= n <= 200000; the value and next-index lines each contain exactly n tokens.", "Every next index and the head are -1 or in [0,n); unreachable nodes do not affect the answer."],
 ["First detect a slow/fast meeting.", "Reset one pointer to the head.", "Their next meeting is the entry."],
 "O(n) time, O(n) auxiliary space for the next-index serialization",
 P("int n=in.nextInt();for(int i=0;i<n;i++)in.nextInt();int[]next=new int[n];for(int i=0;i<n;i++)next[i]=in.nextInt();int head=in.nextInt(),slow=head,fast=head;while(fast!=-1&&next[fast]!=-1){slow=next[slow];fast=next[next[fast]];if(slow==fast){slow=head;while(slow!=fast){slow=next[slow];fast=next[fast];}System.out.println(slow);return;}}System.out.println(-1);"),
 [C("4\n3 2 0 -4\n1 2 3 1\n0\n","1"), C("3\n1 2 3\n1 2 -1\n0\n","-1")],
 [C("0\n\n\n-1\n","-1"), C("1\n1\n0\n0\n","0"), C("5\n0 0 0 0 0\n1 2 3 4 2\n0\n","2"), C("4\n4 5 6 7\n-1 0 1 2\n0\n","-1")],
),
D(109,"Binary Tree Zigzag Levels","Easy","trees","Line 1 is n; each following line is a node value, left-child index, right-child index (-1 absent). Root is 0. Print values level by level, reversing the order on every odd-numbered depth.",["0 <= n <= 1900; child indices form one acyclic tree rooted at 0.","Values fit signed 32-bit integers; the bound keeps output below the local runner limit."],["Breadth-first traversal isolates one level at a time.","Reverse only the values of alternate levels.","An empty tree prints an empty line."],"O(n) time, O(n) auxiliary space",P("int n=in.nextInt();int[]v=new int[n],l=new int[n],r=new int[n];for(int i=0;i<n;i++){v[i]=in.nextInt();l[i]=in.nextInt();r[i]=in.nextInt();}if(n==0){System.out.println();return;}ArrayDeque<Integer>q=new ArrayDeque<>();q.add(0);List<Integer>a=new ArrayList<>();int dep=0;boolean first=true;while(!q.isEmpty()){int z=q.size();a.clear();while(z-->0){int x=q.remove();a.add(v[x]);if(l[x]>=0)q.add(l[x]);if(r[x]>=0)q.add(r[x]);}if((dep++&1)==1)Collections.reverse(a);for(int x:a){if(!first)System.out.print(\" \");first=false;System.out.print(x);}}System.out.println();"),[C("3\n1 1 2\n2 -1 -1\n3 -1 -1\n","1 3 2"),C("0\n","")],[C("1\n9 -1 -1\n","9"),C("4\n1 1 2\n2 3 -1\n3 -1 -1\n4 -1 -1\n","1 3 2 4"),C("5\n1 1 2\n2 3 4\n3 -1 -1\n4 -1 -1\n5 -1 -1\n","1 3 2 4 5"),C("3\n-1 1 -1\n-2 2 -1\n-3 -1 -1\n","-1 -2 -3")]),
D(
 110, "Binary Tree Diameter Edges", "Medium", "trees",
 "Line 1 is n; the next n lines give every node's left and right child index (-1 is absent). Print the tree diameter in edges; root is 0.",
 ["0 <= n <= 200000; child indices are -1 or in [0,n).", "For n>0 the indices form one acyclic tree rooted at 0; children need not have larger indices than parents."],
 ["A node's best path joins its two child heights.", "Build a traversal order, then compute heights backwards.", "An empty tree has diameter zero."],
 "O(n) time, O(n) auxiliary space",
 P("int n=in.nextInt();int[]l=new int[n],r=new int[n],h=new int[n];for(int i=0;i<n;i++){l[i]=in.nextInt();r[i]=in.nextInt();}if(n==0){System.out.println(0);return;}int[]stack=new int[n],order=new int[n];int top=0,count=0;stack[top++]=0;while(top>0){int u=stack[--top];order[count++]=u;if(l[u]>=0)stack[top++]=l[u];if(r[u]>=0)stack[top++]=r[u];}int ans=0;for(int z=count-1;z>=0;z--){int u=order[z],a=l[u]<0?0:h[l[u]],b=r[u]<0?0:h[r[u]];ans=Math.max(ans,a+b);h[u]=1+Math.max(a,b);}System.out.println(ans);"),
 [C("3\n1 2\n-1 -1\n-1 -1\n","2"), C("0\n","0")],
 [C("1\n-1 -1\n","0"), C("4\n1 -1\n2 -1\n3 -1\n-1 -1\n","3"), C("4\n2 1\n-1 3\n-1 -1\n-1 -1\n","3"), C("5\n1 2\n3 4\n-1 -1\n-1 -1\n-1 -1\n","3")],
),
D(111,"Tree Ancestor Query","Easy","trees","Line 1 is n, line 2 is a parent array, and line 3 gives nodes a b. Print their lowest common ancestor.",["1 <= n <= 200000; a and b are in [0,n).","The parent array forms one rooted tree and contains exactly one -1 root."],["Mark a's ancestors.","Walk b upward.","First marked node wins."],"O(tree height) time, O(n + tree height) auxiliary space including the parent array",P("int n=in.nextInt();int[]p=new int[n];for(int i=0;i<n;i++)p[i]=in.nextInt();int a=in.nextInt(),b=in.nextInt();Set<Integer>s=new HashSet<>();while(a>=0){s.add(a);a=p[a];}while(!s.contains(b))b=p[b];System.out.println(b);"),[C("5\n-1 0 0 1 1\n3 4\n","1"),C("3\n-1 0 0\n1 2\n","0")],[C("1\n-1\n0 0\n","0"),C("4\n-1 0 1 2\n3 2\n","2"),C("4\n-1 0 0 2\n1 3\n","0"),C("6\n-1 0 0 1 1 2\n4 5\n","0")]),
D(112,"Sorted Matrix Membership","Medium","matrices","Line 1 contains rows, columns, and target, followed by a row-and-column nondecreasing matrix. Print true when target occurs.",["0 <= rows,cols <= 500.","Matrix values and target fit signed 32-bit integers."],["Begin top right.","Large values remove columns.","Small values remove rows."],"O(rows+cols) time, O(rows*cols) auxiliary space for the matrix",P("int r=in.nextInt(),c=in.nextInt(),t=in.nextInt();int[][]a=new int[r][c];for(int i=0;i<r;i++)for(int j=0;j<c;j++)a[i][j]=in.nextInt();int i=0,j=c-1;while(i<r&&j>=0){if(a[i][j]==t){System.out.println(\"true\");return;}if(a[i][j]>t)j--;else i++;}System.out.println(\"false\");"),[C("3 3 5\n1 4 7\n2 5 8\n3 6 9\n","true"),C("2 2 4\n1 2\n3 5\n","false")],[C("0 0 1\n","false"),C("1 1 -2\n-2\n","true"),C("2 3 6\n1 2 3\n4 5 6\n","true"),C("2 3 0\n1 2 3\n4 5 6\n","false")]),
D(113,"Running Lower Median","Hard","heaps","Line 1 is n and line 2 is a stream of n integers. Print the lower median after every insertion.",["1 <= n <= 1900.","Values fit signed 32-bit integers; the bound keeps output below the local runner limit."],["Split values into two heaps.","Lower heap owns equal extra value.","Rebalance after every insertion."],"O(n log n) time, O(n) auxiliary space",P("int n=in.nextInt();PriorityQueue<Integer>l=new PriorityQueue<>(Collections.reverseOrder()),h=new PriorityQueue<>();for(int i=0;i<n;i++){int x=in.nextInt();if(l.isEmpty()||x<=l.peek())l.add(x);else h.add(x);if(l.size()<h.size())l.add(h.remove());if(l.size()>h.size()+1)h.add(l.remove());if(i>0)System.out.print(\" \");System.out.print(l.peek());}System.out.println();"),[C("4\n5 15 1 3\n","5 5 5 3"),C("3\n2 1 3\n","2 1 2")],[C("1\n7\n","7"),C("4\n1 2 3 4\n","1 1 2 2"),C("3\n-1 -2 -3\n","-1 -2 -2"),C("5\n5 5 5 5 5\n","5 5 5 5 5")]),
D(
 114, "Kth Pair Distance", "Hard", "binary-search",
 "Line 1 contains n and 1-based k; line 2 contains n integers. Print the kth smallest absolute distance among unordered index pairs.",
 ["2 <= n <= 50000 and 1 <= k <= n*(n-1)/2.", "Values fit in signed 32-bit integers, so distances and search bounds use long."],
 ["Sort values.", "Count close pairs with two pointers.", "Binary-search distance."],
 "O(n log n + n log distanceRange) time, O(n) auxiliary space",
 P("int n=in.nextInt();long k=in.nextLong();int[]a=new int[n];for(int i=0;i<n;i++)a[i]=in.nextInt();Arrays.sort(a);long l=0,r=(long)a[n-1]-a[0];while(l<r){long m=l+(r-l)/2,z=0;int i=0;for(int j=0;j<n;j++){while((long)a[j]-a[i]>m)i++;z+=j-i;}if(z>=k)r=m;else l=m+1;}System.out.println(l);"),
 [C("3 1\n1 3 1\n","0"), C("3 2\n1 6 1\n","5")],
 [C("2 1\n0 10\n","10"), C("4 3\n1 2 3 4\n","1"), C("4 6\n1 2 3 4\n","3"), C("3 3\n-2147483648 0 2147483647\n","4294967295")],
),
D(115,"N Queens Count","Hard","backtracking","Print how many n-queen placements exist.",["0 <= n <= 12."],["Place by row.","Track columns and both diagonals.","Completed board counts once."],"O(n!) time, O(n) auxiliary space",P("int n=in.nextInt();System.out.println(f(0,n,0,0,0));","static long f(int r,int n,int c,int a,int b){if(r==n)return 1;long z=0;for(int x=0;x<n;x++){int q=1<<x,u=1<<(r+x),v=1<<(r-x+n-1);if((c&q)==0&&(a&u)==0&&(b&v)==0)z+=f(r+1,n,c|q,a|u,b|v);}return z;}"),[C("4\n","2"),C("1\n","1")],[C("0\n","1"),C("2\n","0"),C("5\n","10"),C("8\n","92")]),
D(116,"Balanced Parenthesis Count","Medium","dynamic-programming","Print the number of balanced strings with n pairs.",["0 <= n <= 18."],["Use Catalan recurrence.","Split after first matching close.","Combine smaller counts."],"O(n^2) time, O(n) auxiliary space",P("int n=in.nextInt();long[]d=new long[n+1];d[0]=1;for(int i=1;i<=n;i++)for(int j=0;j<i;j++)d[i]+=d[j]*d[i-j-1];System.out.println(d[n]);"),[C("3\n","5"),C("0\n","1")],[C("1\n","1"),C("2\n","2"),C("4\n","14"),C("10\n","16796")]),
D(
 117, "Minimum Dictionary Segments", "Medium", "dynamic-programming",
 "The first token is nonempty lowercase text, followed by dictionary size m and m nonempty lowercase words. Print the fewest words forming the text, or -1.",
 ["1 <= text length <= 10000 and 0 <= m <= 10000.", "Total dictionary length D is at most 100000; duplicate words are allowed."],
 ["Build a trie of dictionary prefixes.", "Start a trie walk only at a reachable text position.", "A terminal trie node can improve the endpoint's segment count."],
 "O(D + textLength * longestWordLength) time, O(26*D + textLength) auxiliary space",
 P("String s=in.next();int m=in.nextInt(),total=0;String[]words=new String[m];for(int i=0;i<m;i++){words[i]=in.next();total+=words[i].length();}int[][]next=new int[total+1][26];boolean[]end=new boolean[total+1];int nodes=1;for(String word:words){int u=0;for(char ch:word.toCharArray()){int c=ch-'a';if(next[u][c]==0)next[u][c]=nodes++;u=next[u][c];}end[u]=true;}int[]dp=new int[s.length()+1];Arrays.fill(dp,1000000000);dp[0]=0;for(int i=0;i<s.length();i++){if(dp[i]==1000000000)continue;int u=0;for(int j=i;j<s.length();j++){u=next[u][s.charAt(j)-'a'];if(u==0)break;if(end[u])dp[j+1]=Math.min(dp[j+1],dp[i]+1);}}System.out.println(dp[s.length()]==1000000000?-1:dp[s.length()]);"),
 [C("leetcode 2\nleet code\n","2"), C("catsandog 5\ncats dog sand and cat\n","-1")],
 [C("a 1\na\n","1"), C("aaaa 2\na aa\n","2"), C("applepenapple 2\napple pen\n","3"), C("abc 2\nab bc\n","-1")],
),
D(118,"Edit Distance","Hard","dynamic-programming","Print edit distance between two input lines.",["Line length <= 2000."],["Keep two DP directions.","Equal characters use diagonal.","Otherwise choose cheapest edit."],"O(mn) time, O(n) auxiliary space",P("String a=in.nextLine(),b=in.nextLine();int[]d=new int[b.length()+1];for(int j=0;j<=b.length();j++)d[j]=j;for(int i=1;i<=a.length();i++){int q=d[0]++;for(int j=1;j<=b.length();j++){int old=d[j];d[j]=a.charAt(i-1)==b.charAt(j-1)?q:1+Math.min(q,Math.min(d[j],d[j-1]));q=old;}}System.out.println(d[b.length()]);"),[C("horse\nros\n","3"),C("intention\nexecution\n","5")],[C("\nabc\n","3"),C("abc\n\n","3"),C("same\nsame\n","0"),C("a\nb\n","1")]),
D(119,"Minimum Palindrome Cuts","Hard","dynamic-programming","Read one printable-ASCII line and print the fewest cuts that partition it into nonempty palindromic substrings.",["0 <= line length <= 2000."],["Expand each palindrome center.","Update best prefix cuts.","A prefix palindrome costs zero."],"O(n^2) time, O(n) auxiliary space",P("String s=in.nextLine();int n=s.length();int[]d=new int[n];for(int i=0;i<n;i++)d[i]=i;for(int c=0;c<n;c++)for(int z=0;z<2;z++)for(int l=c,r=c+z;l>=0&&r<n&&s.charAt(l)==s.charAt(r);l--,r++)d[r]=Math.min(d[r],l==0?0:d[l-1]+1);System.out.println(n==0?0:d[n-1]);"),[C("aab\n","1"),C("a\n","0")],[C("\n","0"),C("ab\n","1"),C("racecar\n","0"),C("banana\n","1")]),
D(120,"Maximal One Rectangle","Hard","matrices","Print largest all-one rectangle area in a binary matrix.",["0 <= rows,cols <= 500."],["Treat rows as histogram bases.","Use increasing stack indices.","Pop at a shorter bar."],"O(rows*cols) time, O(cols) auxiliary space",P("int r=in.nextInt(),c=in.nextInt(),ans=0;int[]h=new int[c+1];for(int i=0;i<r;i++){for(int j=0;j<c;j++)h[j]=in.nextInt()==1?h[j]+1:0;Deque<Integer>s=new ArrayDeque<>();for(int j=0;j<=c;j++){while(!s.isEmpty()&&h[s.peek()]>=h[j]){int x=s.pop(),l=s.isEmpty()?-1:s.peek();ans=Math.max(ans,h[x]*(j-l-1));}s.push(j);}}System.out.println(ans);"),[C("2 3\n1 0 1\n1 1 1\n","3"),C("1 4\n1 1 1 1\n","4")],[C("0 0\n","0"),C("2 2\n0 0\n0 0\n","0"),C("3 2\n1 1\n1 1\n1 0\n","4"),C("2 3\n1 1 0\n1 1 1\n","4")]),
]
assert [x["id"] for x in JAVA_CURRICULUM_PART3]==[f"java-curated-{n:03d}" for n in range(101,121)]
