"""Final advanced SQL curriculum tranche (records 126 through 150).

The catalogue is data-only when imported.  Expected results are an offline
literal snapshot in :mod:`sql_curriculum_part2_oracles`; SQLite is used only by
the explicit validation helper.
"""
from __future__ import annotations

from typing import Any

from .sql_curriculum_part2_oracles import ORACLE_OUTPUTS

STARTER = "-- Write one read-only SELECT or WITH query in the selected dialect.\n"
SCHEMA = "Schemas vary by drill; use the table declarations supplied in its constraints."

_BASE = """
CREATE TABLE employees(id INTEGER PRIMARY KEY, name TEXT, department TEXT, manager_id INTEGER, salary INTEGER, parent_id INTEGER);
CREATE TABLE skills(employee_id INTEGER, skill TEXT);
CREATE TABLE required_skills(skill TEXT);
CREATE TABLE categories(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE products(id INTEGER PRIMARY KEY, category_id INTEGER, name TEXT);
CREATE TABLE customers(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE orders(id INTEGER PRIMARY KEY, customer_id INTEGER, product_id INTEGER, amount INTEGER, status TEXT, ordered_at TEXT);
CREATE TABLE events(id INTEGER PRIMARY KEY, user_id INTEGER, kind TEXT, occurred_at TEXT);
CREATE TABLE inventory(id INTEGER PRIMARY KEY, product_id INTEGER, changed_at TEXT, quantity_delta INTEGER);
CREATE TABLE subscriptions(id INTEGER PRIMARY KEY, customer_id INTEGER, starts_on TEXT, ends_on TEXT);
CREATE TABLE flights(id INTEGER PRIMARY KEY, origin TEXT, destination TEXT, departs_at TEXT, arrives_at TEXT, fare INTEGER);
CREATE TABLE source_rows(id INTEGER PRIMARY KEY, natural_key TEXT, value TEXT, updated_at TEXT);
INSERT INTO employees VALUES (1,'Ada','Eng',NULL,120,NULL),(2,'Ben','Eng',1,100,1),(3,'Cy','Eng',1,100,1),(4,'Dee','Sales',NULL,90,NULL),(5,'Eli','Sales',4,80,4),(6,'Fox','Support',NULL,70,NULL),(7,'Gia','Eng',2,95,2),(8,'Hal','Sales',5,75,5);
INSERT INTO skills VALUES (1,'sql'),(1,'python'),(2,'sql'),(2,'python'),(3,'sql'),(4,'sql'),(4,'python'),(4,'excel'),(5,'sql'),(6,'python');
INSERT INTO required_skills VALUES ('sql'),('python');
INSERT INTO categories VALUES (1,'Books'),(2,'Games'),(3,'Home');
INSERT INTO products VALUES (1,1,'Novel'),(2,1,'Atlas'),(3,2,'Chess'),(4,2,'Cards'),(5,3,'Lamp');
INSERT INTO customers VALUES (1,'Ana'),(2,'Bo'),(3,'Cy'),(4,'Di');
INSERT INTO orders VALUES (1,1,1,100,'paid','2024-01-05'),(2,1,3,50,'paid','2024-02-10'),(3,1,3,70,'paid','2024-03-11'),(4,2,2,40,'paid','2024-01-20'),(5,2,4,30,'pending','2024-02-21'),(6,2,3,60,'paid','2024-03-22'),(7,3,1,20,'paid','2024-01-02'),(8,3,5,25,'paid','2024-03-05');
INSERT INTO events VALUES (1,1,'signup','2024-01-01 09:00'),(2,1,'activate','2024-01-02 09:00'),(3,1,'purchase','2024-01-04 09:00'),(4,2,'signup','2024-01-03 09:00'),(5,2,'purchase','2024-01-08 09:00'),(6,3,'signup','2024-02-01 09:00'),(7,3,'activate','2024-02-01 10:00'),(8,3,'purchase','2024-02-03 11:00'),(9,1,'login','2024-02-10 09:00'),(10,1,'login','2024-02-10 09:20'),(11,1,'login','2024-02-10 10:05'),(12,2,'login','2024-02-11 09:00'),(13,2,'login','2024-02-11 09:45'),(14,1,'view','2024-02-10 09:10'),(15,1,'view','2024-02-14 09:10'),(16,1,'view','2024-02-16 09:10'),(17,2,'view','2024-02-16 09:10');
INSERT INTO inventory VALUES (1,1,'2024-01-01',10),(2,1,'2024-01-05',-4),(3,1,'2024-01-10',-8),(4,2,'2024-01-02',5),(5,2,'2024-01-08',-2);
INSERT INTO subscriptions VALUES (1,1,'2024-01-15','2024-03-10'),(2,2,'2024-02-01',NULL),(3,3,'2024-03-20','2024-03-25');
INSERT INTO flights VALUES (1,'A','B','2024-04-01 08:00','2024-04-01 09:00',100),(2,'B','C','2024-04-01 10:00','2024-04-01 11:00',80),(3,'A','C','2024-04-01 07:00','2024-04-01 10:30',250),(4,'C','D','2024-04-01 12:00','2024-04-01 13:00',70),(5,'B','D','2024-04-01 09:30','2024-04-01 10:30',120);
INSERT INTO source_rows VALUES (1,'a','old','2024-01-01'),(2,'a','new','2024-01-02'),(3,'b','only','2024-01-01'),(4,'c','first','2024-01-03'),(5,'c','second','2024-01-03');
"""

def _cases(key: str, mutations: tuple[str, ...]) -> list[dict[str, str]]:
    assert len(mutations) == 6
    return [{"input": "", "setup_sql": _BASE + mutation, "expected_output": ORACLE_OUTPUTS[key][i]} for i, mutation in enumerate(mutations)]

def _item(number: int, title: str, difficulty: str, family: str, description: str, solution: str, hints: tuple[str, str, str], complexity: str, mutations: tuple[str, ...], schema: str) -> dict[str, Any]:
    key = f"sql-curated-{number:03d}"
    cases = _cases(key, mutations)
    return {"id": key, "title": title, "language": "sql", "difficulty": difficulty, "topics": [family], "curriculum_family": family, "practice_frequency": "Common", "description": description, "constraints": ["Write one read-only SELECT or WITH query in the selected dialect.", "The selected dialect is translated for local SQLite compatibility before judging.", "Return columns in exactly the requested order.", schema], "examples": [{"input": "", "output": cases[0]["expected_output"], "explanation": "The managed example illustrates the contract; hidden datasets alter the named edge conditions."}], "starter_code": STARTER, "solution": solution, "hints": list(hints), "expected_complexity": complexity, "public_tests": cases[:2], "hidden_tests": cases[2:], "sql_setup": cases[0]["setup_sql"]}

E = "Schema: employees(id, name, department, manager_id, salary, parent_id); skills(employee_id, skill); required_skills(skill); categories(id, name); products(id, category_id, name); customers(id, name); orders(id, customer_id, status, ordered_at); order_lines(order_id, product_id, quantity, unit_price); events(id, user_id, employee_id, event_type, occurred_at); inventory_changes(id, product_id, changed_at, delta); subscriptions(id, start_date, end_date); flights(id, origin, destination, departs_at, arrives_at, fare); versions(id, natural_key, value, updated_at)"
O = "Schema: customers(id, name); categories(id, name); products(id, category_id, name); orders(id, customer_id, product_id, amount, status, ordered_at)"
V = "Schema: events(id, user_id, kind, occurred_at)"
I = "Schema: inventory(id, product_id, changed_at, quantity_delta)"
S = "Schema: subscriptions(id, customer_id, starts_on, ends_on)"
F = "Schema: flights(id, origin, destination, departs_at, arrives_at, fare)"
R = "Schema: source_rows(id, natural_key, value, updated_at)"

_M = {
 "salary": ("", "INSERT INTO employees VALUES (9,'Ivy','Eng',1,110,1);", "UPDATE employees SET salary=120 WHERE id=2;", "INSERT INTO employees VALUES (9,'Ivy','Sales',4,85,4);", "DELETE FROM employees WHERE id=5;", "INSERT INTO employees VALUES (9,'Ivy','Support',6,70,6);"),
 "orders": ("", "INSERT INTO orders VALUES (9,4,5,35,'paid','2024-04-01');", "UPDATE orders SET amount=0 WHERE id=3;", "INSERT INTO orders VALUES (9,1,1,40,'paid','2024-02-15');", "DELETE FROM orders WHERE id=6;", "UPDATE orders SET status='paid' WHERE id=5;"),
 "events": ("", "INSERT INTO events VALUES (18,1,'view','2024-02-15 09:10');", "INSERT INTO events VALUES (18,2,'login','2024-02-11 09:20');", "UPDATE events SET occurred_at='2024-02-10 09:55' WHERE id=11;", "DELETE FROM events WHERE id=16;", "INSERT INTO events VALUES (18,3,'view','2024-02-17 09:10');"),
 "skills": ("", "INSERT INTO skills VALUES (3,'python');", "DELETE FROM skills WHERE employee_id=4 AND skill='excel';", "INSERT INTO required_skills VALUES ('excel');", "DELETE FROM required_skills WHERE skill='python';", "INSERT INTO skills VALUES (5,'python');"),
 "tree": ("", "INSERT INTO employees VALUES (9,'Ivy','Eng',2,65,2);", "UPDATE employees SET parent_id=4 WHERE id=8;", "INSERT INTO employees VALUES (9,'Ivy','Support',6,65,6);", "UPDATE employees SET parent_id=2 WHERE id=3;", "UPDATE employees SET parent_id=1 WHERE id=8;"),
 "catalog": ("", "INSERT INTO orders VALUES (9,4,5,35,'paid','2024-04-01');", "INSERT INTO orders VALUES (9,2,4,60,'paid','2024-03-23');", "DELETE FROM orders WHERE id=8;", "UPDATE orders SET status='paid' WHERE id=5;", "INSERT INTO products VALUES (6,3,'Sofa');"),
 "inventory": ("", "INSERT INTO inventory VALUES (6,1,'2024-01-12',5);", "UPDATE inventory SET quantity_delta=-1 WHERE id=2;", "INSERT INTO inventory VALUES (6,2,'2024-01-09',-5);", "DELETE FROM inventory WHERE id=3;", "INSERT INTO inventory VALUES (6,3,'2024-01-01',-2);"),
 "subs": ("", "INSERT INTO subscriptions VALUES (4,4,'2024-01-01','2024-01-31');", "UPDATE subscriptions SET ends_on='2024-02-20' WHERE id=2;", "INSERT INTO subscriptions VALUES (4,1,'2024-04-01',NULL);", "DELETE FROM subscriptions WHERE id=3;", "UPDATE subscriptions SET starts_on='2024-02-15' WHERE id=2;"),
 "flights": ("", "INSERT INTO flights VALUES (6,'A','D','2024-04-01 08:30','2024-04-01 09:30',300);", "INSERT INTO flights VALUES (6,'B','D','2024-04-01 11:30','2024-04-01 12:30',50);", "DELETE FROM flights WHERE id=2;", "INSERT INTO flights VALUES (6,'A','B','2024-04-01 06:00','2024-04-01 07:00',90);", "UPDATE flights SET fare=60 WHERE id=3;"),
 "dedup": ("", "INSERT INTO source_rows VALUES (6,'b','later','2024-01-04');", "UPDATE source_rows SET updated_at='2024-01-05' WHERE id=1;", "INSERT INTO source_rows VALUES (6,'d','only','2024-01-01');", "DELETE FROM source_rows WHERE id=2;", "INSERT INTO source_rows VALUES (6,'c','third','2024-01-04');"),
}

_ITEMS = [
_item(126,'Second distinct salary per department','Medium','window-ranking','For each department that has at least two distinct salaries, return department and its second_highest_distinct_salary. Equal salaries count once. Sort department.', "WITH r AS (SELECT department,salary,DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) rnk FROM employees) SELECT department,salary AS second_highest_distinct_salary FROM r WHERE rnk=2 ORDER BY department", ('Rank distinct salary values within each department.','Use dense ranking so salary ties share a position.','Keep only position two.'), 'Partitioned dense rank.', _M['salary'], E),
_item(127,'Department salary percent ranks','Medium','window-ranking','Return department, name, salary and salary_percent_rank for every employee. Percent rank is based on salary ascending within a department; equal salaries share the same value. Sort department, salary, name.', "SELECT department,name,salary,PERCENT_RANK() OVER (PARTITION BY department ORDER BY salary) AS salary_percent_rank FROM employees ORDER BY department,salary,name", ('Partition the analytical window by department.','Do not add name to the percent-rank ordering.','Use name only for display ties.'), 'One partitioned ranking window.', _M['salary'], E),
_item(128,'Department salary quartiles','Medium','window-ranking','Return department, name, salary and salary_quartile from one through four, assigning employees by salary descending and name ascending. Sort department, salary_quartile, name.', "SELECT department,name,salary,NTILE(4) OVER (PARTITION BY department ORDER BY salary DESC,name) AS salary_quartile FROM employees ORDER BY department,salary_quartile,name", ('NTILE divides each department independently.','Specify deterministic salary tie ordering.','Sort by the displayed bucket afterwards.'), 'Partitioned NTILE window.', _M['salary'], E),
_item(129,'Monthly paid revenue change','Medium','time-series','For every calendar month containing a paid order, return month, paid_revenue and change_from_previous_month. The first returned month has NULL change. Sort month.', "WITH m AS (SELECT substr(ordered_at,1,7) month,SUM(amount) paid_revenue FROM orders WHERE status='paid' GROUP BY 1) SELECT month,paid_revenue,paid_revenue-LAG(paid_revenue) OVER (ORDER BY month) AS change_from_previous_month FROM m ORDER BY month", ('Aggregate paid orders before comparing months.','LAG belongs after the monthly grouping.','Keep the first change as NULL.'), 'Monthly aggregate plus LAG.', _M['orders'], O),
_item(130,'Monthly paid revenue growth rate','Medium','time-series','For every calendar month containing a paid order, return month, paid_revenue and growth_percent from the prior returned month. Return NULL when the prior revenue is zero or absent; otherwise use 100.0 times the change divided by prior revenue. Sort month.', "WITH m AS (SELECT substr(ordered_at,1,7) month,SUM(amount) paid_revenue FROM orders WHERE status='paid' GROUP BY 1), x AS (SELECT month,paid_revenue,LAG(paid_revenue) OVER (ORDER BY month) prior FROM m) SELECT month,paid_revenue,CASE WHEN prior IS NULL OR prior=0 THEN NULL ELSE 100.0*(paid_revenue-prior)/prior END AS growth_percent FROM x ORDER BY month", ('Calculate the prior month once in a CTE.','Guard the zero denominator explicitly.','Use floating-point arithmetic for percentages.'), 'Monthly aggregate plus guarded LAG.', _M['orders'], O),
_item(131,'Rolling seven-day event counts','Hard','time-series','For each view event, return id, user_id, occurred_at and view_events_in_prior_7_days: views for that user from six calendar days before through the event date, including same-time rows. Sort user_id, occurred_at, id.', "SELECT e.id,e.user_id,e.occurred_at,(SELECT COUNT(*) FROM events p WHERE p.user_id=e.user_id AND p.kind='view' AND date(p.occurred_at) BETWEEN date(e.occurred_at,'-6 days') AND date(e.occurred_at)) AS view_events_in_prior_7_days FROM events e WHERE e.kind='view' ORDER BY e.user_id,e.occurred_at,e.id", ('A calendar range is different from a preceding-row frame.','Correlate the count to the current user and date.','Include both range endpoints.'), 'Correlated date-range count.', _M['events'], V),
_item(132,'Login sessionization','Hard','gaps-and-islands','For login events, split each user into sessions whenever the gap from the previous login is greater than 30 minutes. Process equal timestamps in id order. Return user_id, session_number, session_start, session_end and login_count. Sort user_id, session_number.', "WITH x AS (SELECT user_id,occurred_at,id,LAG(occurred_at) OVER (PARTITION BY user_id ORDER BY occurred_at,id) p FROM events WHERE kind='login'), y AS (SELECT *,SUM(CASE WHEN p IS NULL OR (julianday(occurred_at)-julianday(p))*1440>30 THEN 1 ELSE 0 END) OVER (PARTITION BY user_id ORDER BY occurred_at,id ROWS UNBOUNDED PRECEDING) s FROM x) SELECT user_id,s AS session_number,MIN(occurred_at) session_start,MAX(occurred_at) session_end,COUNT(*) login_count FROM y GROUP BY user_id,s ORDER BY user_id,s", ("Find each user's preceding login first.",'Mark a new session on a gap strictly over 30 minutes.','Cumulatively sum the markers before grouping.'), 'Two windows and grouped session islands.', _M['events'], V),
_item(133,'Longest login session span','Medium','session-analysis',"Using the same greater-than-30-minute session boundary, with equal timestamps processed in id order, return user_id, session_start, session_end and span_minutes for each user's longest session. Break equal spans by earlier session_start. Sort user_id.", "WITH x AS (SELECT user_id,occurred_at,id,LAG(occurred_at) OVER (PARTITION BY user_id ORDER BY occurred_at,id) p FROM events WHERE kind='login'), y AS (SELECT *,SUM(CASE WHEN p IS NULL OR (julianday(occurred_at)-julianday(p))*1440>30 THEN 1 ELSE 0 END) OVER (PARTITION BY user_id ORDER BY occurred_at,id ROWS UNBOUNDED PRECEDING) s FROM x), z AS (SELECT user_id,s,MIN(occurred_at) a,MAX(occurred_at) b FROM y GROUP BY user_id,s), r AS (SELECT *,ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY (julianday(b)-julianday(a))*1440 DESC,a) n FROM z) SELECT user_id,a AS session_start,b AS session_end,CAST((julianday(b)-julianday(a))*1440 AS INTEGER) AS span_minutes FROM r WHERE n=1 ORDER BY user_id", ('Build sessions before choosing the longest one.','Rank the grouped sessions within each user.','Use earliest start as the equal-span tie-breaker.'), 'Session islands plus partitioned ranking.', ("", "INSERT INTO events VALUES (18,1,'login','2024-02-10 09:25');", "UPDATE events SET occurred_at='2024-02-11 09:20' WHERE id=13;", "INSERT INTO events VALUES (18,3,'login','2024-02-12 08:00'),(19,3,'login','2024-02-12 08:29');", "DELETE FROM events WHERE id=10;", "UPDATE events SET occurred_at='2024-02-10 09:50' WHERE id=11;"), V),
_item(134,'Ordered signup activation conversion','Hard','event-sequencing','Return user_id values that have an activate event strictly after a signup event for the same user. A premature activation does not qualify. Return each user once, sorted user_id.', "SELECT DISTINCT s.user_id FROM events s JOIN events a ON a.user_id=s.user_id AND a.kind='activate' AND a.occurred_at>s.occurred_at WHERE s.kind='signup' ORDER BY s.user_id", ('Represent signup and activation as separate event roles.','Compare timestamps within the same user.','Use DISTINCT when a user has multiple matching pairs.'), 'Self join with ordered event predicate.', ("", "INSERT INTO events VALUES (18,2,'activate','2024-01-02 09:00');", "INSERT INTO events VALUES (18,2,'activate','2024-01-04 09:00');", "INSERT INTO events VALUES (18,3,'activate','2024-01-31 09:00');", "DELETE FROM events WHERE id=2;", "INSERT INTO events VALUES (18,4,'signup','2024-03-01 09:00'),(19,4,'activate','2024-03-01 10:00');"), V),
_item(135,'Signup to first later purchase','Medium','event-sequencing','For every signup event with a later purchase by the same user, return user_id, signup_at, first_purchase_at and hours_to_first_purchase. Treat equal timestamps as not later. Sort user_id, signup_at.', "SELECT s.user_id,s.occurred_at AS signup_at,MIN(p.occurred_at) AS first_purchase_at,CAST((julianday(MIN(p.occurred_at))-julianday(s.occurred_at))*24 AS INTEGER) AS hours_to_first_purchase FROM events s JOIN events p ON p.user_id=s.user_id AND p.kind='purchase' AND p.occurred_at>s.occurred_at WHERE s.kind='signup' GROUP BY s.id,s.user_id,s.occurred_at ORDER BY s.user_id,s.occurred_at", ('Join each signup to strictly later purchases.','Take the minimum matching purchase time.','Calculate the duration after choosing that time.'), 'Ordered self join and grouped minimum.', ("", "INSERT INTO events VALUES (18,2,'purchase','2024-01-04 09:00');", "INSERT INTO events VALUES (18,3,'purchase','2024-02-01 09:00');", "INSERT INTO events VALUES (18,3,'purchase','2024-02-02 09:00');", "DELETE FROM events WHERE id=3;", "INSERT INTO events VALUES (18,4,'signup','2024-03-01 09:00'),(19,4,'purchase','2024-03-03 09:00');"), V),
_item(136,'Employees missing exactly one required skill','Medium','relational-division','Return id and name for employees missing exactly one distinct value from required_skills. Duplicate skill rows must not change the result. If requirements are empty, nobody is missing exactly one. Sort id.', "SELECT e.id,e.name FROM employees e LEFT JOIN required_skills r ON 1=1 LEFT JOIN skills s ON s.employee_id=e.id AND s.skill=r.skill GROUP BY e.id,e.name HAVING COUNT(DISTINCT r.skill)-COUNT(DISTINCT s.skill)=1 ORDER BY e.id", ('Cross each employee with the required skill set.',"Match only that employee's matching skill rows.",'Compare distinct required and matched counts.'), 'Grouped relational division.', _M['skills'], E),
_item(137,'Employees with exactly the required skills','Hard','relational-division','Return id and name for employees whose distinct skill set is exactly the distinct required_skills set: no missing and no extra skills. If requirements are empty, employees with no skills qualify. Sort id.', "SELECT e.id,e.name FROM employees e WHERE NOT EXISTS (SELECT 1 FROM required_skills r WHERE NOT EXISTS (SELECT 1 FROM skills s WHERE s.employee_id=e.id AND s.skill=r.skill)) AND NOT EXISTS (SELECT 1 FROM skills s WHERE s.employee_id=e.id AND NOT EXISTS (SELECT 1 FROM required_skills r WHERE r.skill=s.skill)) ORDER BY e.id", ('Test first for no missing required skills.','Test separately for no employee-only skills.','Two set-containment tests establish equality.'), 'Double relational-division containment.', _M['skills'], E),
_item(138,'Recursive management subtree headcount','Hard','recursive-cte','Assume parent_id relationships form an acyclic forest. For every employee, return id, name and subtree_headcount including that employee and all direct or indirect reports using parent_id. A NULL parent starts a hierarchy. Ignore no rows solely because they are leaves. Sort id.', "WITH RECURSIVE d(root,id) AS (SELECT id,id FROM employees UNION ALL SELECT d.root,e.id FROM d JOIN employees e ON e.parent_id=d.id) SELECT e.id,e.name,COUNT(d.id) AS subtree_headcount FROM employees e JOIN d ON d.root=e.id GROUP BY e.id,e.name ORDER BY e.id", ('Seed each employee as its own subtree root.','Recursively add children below every discovered node.','Count descendants for each original root.'), 'Recursive transitive closure and grouping.', _M['tree'], E),
_item(139,'Recursive management subtree salary','Hard','recursive-cte','Assume parent_id relationships form an acyclic forest. For every employee, return id, name and subtree_salary including that employee and every direct or indirect report using parent_id. Sort id.', "WITH RECURSIVE d(root,id) AS (SELECT id,id FROM employees UNION ALL SELECT d.root,e.id FROM d JOIN employees e ON e.parent_id=d.id) SELECT e.id,e.name,SUM(x.salary) AS subtree_salary FROM employees e JOIN d ON d.root=e.id JOIN employees x ON x.id=d.id GROUP BY e.id,e.name ORDER BY e.id", ('Use the same closure pattern as a subtree count.','Join discovered ids back to salaries.','Aggregate salaries per original root.'), 'Recursive transitive closure and sum.', _M['tree'], E),
_item(140,'Hierarchy parent-link cycles','Hard','recursive-cte','Return start_id values whose parent_id chain eventually repeats an employee id. Exclude chains ending at NULL. Return each start_id once, sorted ascending.', "WITH RECURSIVE walk(start_id,id,path,cycle) AS (SELECT id,id,','||id||',',0 FROM employees UNION ALL SELECT walk.start_id,e.parent_id,walk.path||e.parent_id||',',CASE WHEN instr(walk.path,','||e.parent_id||',')>0 THEN 1 ELSE 0 END FROM walk JOIN employees e ON e.id=walk.id WHERE e.parent_id IS NOT NULL AND walk.cycle=0) SELECT DISTINCT start_id FROM walk WHERE cycle=1 ORDER BY start_id", ('Start a parent walk at every employee.','Carry a delimiter-wrapped id path.','Stop expanding a branch once it repeats.'), 'Recursive path walk with cycle marker.', ("UPDATE employees SET parent_id=1 WHERE id=1;", "UPDATE employees SET parent_id=2 WHERE id=1;", "UPDATE employees SET parent_id=4 WHERE id=4;", "UPDATE employees SET parent_id=8 WHERE id=4;", "UPDATE employees SET parent_id=NULL WHERE id=5;", "UPDATE employees SET parent_id=3 WHERE id=1;"), E),
_item(141,'Category paid sales including zero','Easy','outer-join','Return every category name and its paid_sales. Categories with no paid order lines must show zero. Sort category_name.', "SELECT c.name,COALESCE(SUM(CASE WHEN o.status='paid' THEN o.amount END),0) AS paid_sales FROM categories c LEFT JOIN products p ON p.category_id=c.id LEFT JOIN orders o ON o.product_id=p.id GROUP BY c.id,c.name ORDER BY c.name", ('Start from categories to preserve empty ones.','Follow products before their orders.','Coalesce a missing paid sum to zero.'), 'Two left joins and grouped sum.', _M['catalog'], O),
_item(142,'Top paid product in each category','Medium','window-ranking','For categories with at least one paid order, return category_name, product_name and paid_sales for the highest paid-sales product. Break equal paid_sales by product_name ascending. Sort category_name.', "WITH totals AS (SELECT c.name category_name,p.name product_name,SUM(o.amount) paid_sales FROM categories c JOIN products p ON p.category_id=c.id JOIN orders o ON o.product_id=p.id WHERE o.status='paid' GROUP BY c.id,c.name,p.id,p.name), r AS (SELECT *,ROW_NUMBER() OVER (PARTITION BY category_name ORDER BY paid_sales DESC,product_name) n FROM totals) SELECT category_name,product_name,paid_sales FROM r WHERE n=1 ORDER BY category_name", ('Aggregate sales per product first.','Rank products only after aggregation.','Make the equal-sales tie-breaker explicit.'), 'Aggregate, rank, filter.', _M['catalog'], O),
_item(143,'Customers whose every order is paid','Easy','anti-join','Return id and name for customers whose orders are all paid. A customer with no orders qualifies. Sort id.', "SELECT c.id,c.name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.id AND o.status<>'paid') ORDER BY c.id", ('Look for the disqualifying order status.','NOT EXISTS preserves customers with no orders.','Do not require an order to exist.'), 'Correlated anti-join.', ("", "UPDATE orders SET status='paid' WHERE customer_id=2;", "INSERT INTO orders VALUES (9,4,1,10,'pending','2024-01-01');", "INSERT INTO orders VALUES (9,3,1,10,'refunded','2024-01-01');", "DELETE FROM orders WHERE customer_id=2;", "UPDATE orders SET status='pending' WHERE customer_id=1;"), O),
_item(144,'Customers with three consecutive order months','Hard','gaps-and-islands','Return customer_id values with paid orders in at least three consecutive calendar months. Multiple paid orders in one month count once. Sort customer_id.', "WITH m AS (SELECT DISTINCT customer_id,substr(ordered_at,1,7)||'-01' mon FROM orders WHERE status='paid'), x AS (SELECT customer_id,mon,date(mon,'-'||ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY mon)||' months') grp FROM m), g AS (SELECT customer_id,grp,COUNT(*) n FROM x GROUP BY customer_id,grp) SELECT DISTINCT customer_id FROM g WHERE n>=3 ORDER BY customer_id", ('Deduplicate months before assigning row numbers.','Turn each month into a stable island key.','Keep islands with at least three months.'), 'Monthly deduplication, window, grouping.', ("", "INSERT INTO orders VALUES (9,3,1,10,'paid','2024-02-02');", "INSERT INTO orders VALUES (9,2,1,10,'paid','2024-04-02');", "DELETE FROM orders WHERE id=3;", "UPDATE orders SET status='paid' WHERE id=5;", "INSERT INTO orders VALUES (9,4,1,10,'paid','2024-01-02'),(10,4,1,10,'paid','2024-02-02'),(11,4,1,10,'paid','2024-03-02');"), O),
_item(145,'Order gaps greater than thirty days','Medium','window-lag',"For each customer order after that customer's first, return customer_id, ordered_at, previous_order_at and gap_days when the gap is greater than 30 full days. Sort customer_id, ordered_at.", "WITH x AS (SELECT customer_id,ordered_at,LAG(ordered_at) OVER (PARTITION BY customer_id ORDER BY ordered_at,id) p FROM orders) SELECT customer_id,ordered_at,p AS previous_order_at,CAST(julianday(ordered_at)-julianday(p) AS INTEGER) AS gap_days FROM x WHERE julianday(ordered_at)-julianday(p)>30 ORDER BY customer_id,ordered_at", ("Find each customer's prior order first.",'Compare the actual day difference to 30.','First orders have no prior value and drop out.'), 'Partitioned LAG and date difference.', ("", "INSERT INTO orders VALUES (9,3,1,5,'paid','2024-02-01');", "INSERT INTO orders VALUES (9,1,1,5,'paid','2024-01-20');", "DELETE FROM orders WHERE id=8;", "INSERT INTO orders VALUES (9,4,1,5,'paid','2024-03-15'),(10,4,1,5,'paid','2024-05-01');", "UPDATE orders SET ordered_at='2024-02-25' WHERE id=3;"), O),
_item(146,'Inventory first negative balance','Medium','window-running-total','For each product whose running inventory becomes negative, return product_id and the first changed_at date where it is negative. Apply deltas in changed_at then id order. Sort product_id.', "WITH x AS (SELECT product_id,changed_at,id,SUM(quantity_delta) OVER (PARTITION BY product_id ORDER BY changed_at,id ROWS UNBOUNDED PRECEDING) bal FROM inventory), r AS (SELECT *,ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY changed_at,id) n FROM x WHERE bal<0) SELECT product_id,changed_at AS first_negative_date FROM r WHERE n=1 ORDER BY product_id", ('Compute a deterministic per-product running balance.','Filter balances below zero only after the window.','Rank the negative rows to keep the first.'), 'Running window plus filtered row number.', _M['inventory'], I),
_item(147,'Subscription monthly active snapshots','Medium','recursive-cte','Treat a NULL end as 2024-04-30 for this task. Return month and active_subscriptions for every month from the earliest subscription start through the latest effective end. A subscription is active in a month if its interval overlaps that calendar month. Sort month.', "WITH RECURSIVE b AS (SELECT date(MIN(starts_on),'start of month') a,date(MAX(COALESCE(ends_on,'2024-04-30')),'start of month') z FROM subscriptions), m(month,z) AS (SELECT a,z FROM b UNION ALL SELECT date(month,'+1 month'),z FROM m WHERE month<z) SELECT month,COUNT(s.id) active_subscriptions FROM m LEFT JOIN subscriptions s ON s.starts_on<=date(month,'+1 month','-1 day') AND COALESCE(s.ends_on,'2024-04-30')>=month GROUP BY month ORDER BY month", ('Generate the month calendar from the interval bounds.','Use an overlap predicate, not only the start date.','Apply the stated replacement end date for NULLs.'), 'Recursive month calendar and interval join.', _M['subs'], S),
_item(148,'Flight reachability within two legs','Medium','graph-joins','Return destination airports reachable from A using either one flight or two flights where the second departs no earlier than the first arrives. Exclude A and return each destination once, sorted.', "SELECT DISTINCT destination FROM flights WHERE origin='A' AND destination<>'A' UNION SELECT DISTINCT f2.destination FROM flights f1 JOIN flights f2 ON f2.origin=f1.destination AND f2.departs_at>=f1.arrives_at WHERE f1.origin='A' AND f2.destination<>'A' ORDER BY destination", ('One-leg and two-leg routes are separate populations.','The second departure must respect the first arrival.','UNION removes destinations reached both ways.'), 'One self join and set union.', ("", "DELETE FROM flights WHERE id=3;", "DELETE FROM flights WHERE id IN (2,4,5);", "INSERT INTO flights VALUES (6,'B','E','2024-04-01 11:30','2024-04-01 12:30',50);", "UPDATE flights SET departs_at='2024-04-01 08:30' WHERE id=2;", "INSERT INTO flights VALUES (6,'A','E','2024-04-01 14:00','2024-04-01 15:00',50);"), F),
_item(149,'Cheapest valid two-leg itinerary','Medium','graph-joins','For routes from A to C with exactly two flights and a legal connection, return first_flight_id, second_flight_id and total_fare for the cheapest itinerary. A legal connection has second departure at or after first arrival. Break equal fares by first_flight_id then second_flight_id. Return zero rows if none.', "SELECT f1.id AS first_flight_id,f2.id AS second_flight_id,f1.fare+f2.fare AS total_fare FROM flights f1 JOIN flights f2 ON f2.origin=f1.destination AND f2.departs_at>=f1.arrives_at WHERE f1.origin='A' AND f2.destination='C' ORDER BY total_fare,first_flight_id,second_flight_id LIMIT 1", ('Join a first flight to its connecting second flight.','Enforce the time feasibility in the join.','Order before taking one itinerary.'), 'Self join, sort, limit.', _M['flights'], F),
_item(150,'Newest row per natural key','Easy','data-quality','Return natural_key, value and updated_at after keeping exactly one row per natural_key: the newest updated_at wins, and larger id wins ties. Sort natural_key.', "WITH r AS (SELECT natural_key,value,updated_at,ROW_NUMBER() OVER (PARTITION BY natural_key ORDER BY updated_at DESC,id DESC) n FROM source_rows) SELECT natural_key,value,updated_at FROM r WHERE n=1 ORDER BY natural_key", ('Partition duplicates by their natural key.','Rank newest timestamps first.','Use descending id for equal timestamps.'), 'Partitioned row number.', _M['dedup'], R),
]

SQL_CURRICULUM_PART2 = _ITEMS
assert [x['id'] for x in _ITEMS] == [f'sql-curated-{n:03d}' for n in range(126,151)]

def validate_reference_cases() -> None:
    """Replay the static expected-output snapshot on fresh SQLite databases."""
    import sqlite3
    for record in SQL_CURRICULUM_PART2:
        for case in record['public_tests'] + record['hidden_tests']:
            connection = sqlite3.connect(':memory:')
            try:
                connection.executescript(case['setup_sql'])
                rows = connection.execute(record['solution']).fetchall()
                rendered = '\n'.join('\t'.join('NULL' if v is None else str(v) for v in row) for row in rows)
                assert rendered == case['expected_output'], record['id']
            finally:
                connection.close()
