"""Advanced, independently-authored SQLite interview curriculum (25 drills).

This module is deliberately data-only on import.  Reference output is stored in
``sql_curriculum_part1_oracles`` and can be replayed through the explicit
``validate_reference_cases`` check during tests or release builds.
"""
from __future__ import annotations

from typing import Any

from .sql_curriculum_part1_oracles import ORACLE_OUTPUTS

STARTER = "-- Write one read-only SELECT or WITH query in the selected dialect.\n"
SCHEMA = (
    "Schema: departments(id, name); employees(id, name, department_id, manager_id, "
    "salary, hired_at); orders(id, employee_id, amount, status, ordered_at); "
    "events(id, employee_id, event_type, occurred_at); skills(employee_id, skill); "
    "required_skills(skill)."
)

_BASE = """
CREATE TABLE departments(id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE employees(id INTEGER PRIMARY KEY, name TEXT NOT NULL, department_id INTEGER, manager_id INTEGER, salary INTEGER NOT NULL, hired_at TEXT NOT NULL);
CREATE TABLE orders(id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL, amount INTEGER NOT NULL, status TEXT NOT NULL, ordered_at TEXT NOT NULL);
CREATE TABLE events(id INTEGER PRIMARY KEY, employee_id INTEGER NOT NULL, event_type TEXT NOT NULL, occurred_at TEXT NOT NULL);
CREATE TABLE skills(employee_id INTEGER NOT NULL, skill TEXT NOT NULL);
CREATE TABLE required_skills(skill TEXT NOT NULL);
INSERT INTO departments VALUES (1,'Engineering'),(2,'Sales'),(3,'Support'),(4,'Research');
INSERT INTO employees VALUES (1,'Ada',1,NULL,120,'2022-01-01'),(2,'Ben',1,1,100,'2023-01-01'),(3,'Cy',1,1,100,'2023-06-01'),(4,'Dee',2,NULL,90,'2022-02-01'),(5,'Eli',2,4,80,'2024-01-01'),(6,'Fox',3,NULL,70,'2024-02-01'),(7,'Gia',4,1,110,'2024-03-01'),(8,'Hal',4,7,90,'2024-04-01');
INSERT INTO orders VALUES (1,1,40,'paid','2024-01-01'),(2,1,60,'paid','2024-01-03'),(3,2,30,'paid','2024-01-02'),(4,2,90,'pending','2024-01-04'),(5,4,50,'paid','2024-02-01'),(6,4,70,'paid','2024-02-03'),(7,5,20,'paid','2024-02-02'),(8,7,80,'paid','2024-03-01'),(9,7,100,'paid','2024-03-04');
INSERT INTO events VALUES (1,1,'signup','2024-01-01'),(2,1,'activate','2024-01-02'),(3,1,'purchase','2024-01-03'),(4,2,'signup','2024-01-02'),(5,2,'activate','2024-01-04'),(6,3,'signup','2024-01-05'),(7,4,'signup','2024-02-01'),(8,4,'purchase','2024-02-03'),(9,5,'signup','2024-02-02'),(10,7,'signup','2024-03-01'),(11,7,'activate','2024-03-02'),(12,7,'purchase','2024-03-04');
INSERT INTO skills VALUES (1,'sql'),(1,'python'),(2,'sql'),(3,'python'),(4,'sql'),(4,'python'),(5,'support'),(7,'sql'),(7,'python'),(7,'excel'),(8,'sql');
INSERT INTO required_skills VALUES ('sql'),('python');
"""


def _cases(mutations: tuple[str, ...], key: str) -> list[dict[str, str]]:
    if len(mutations) != 6:
        raise ValueError(f"{key} needs six task-specific datasets")
    return [
        {"input": "", "setup_sql": _BASE + mutation, "expected_output": ORACLE_OUTPUTS[key][index]}
        for index, mutation in enumerate(mutations)
    ]


def _item(
    number: int, title: str, difficulty: str, family: str, description: str,
    solution: str, hints: tuple[str, str, str], complexity: str, mutations: tuple[str, ...],
) -> dict[str, Any]:
    key = f"sql-curated-{number:03d}"
    cases = _cases(mutations, key)
    return {
        "id": key, "title": title, "language": "sql", "difficulty": difficulty,
        "topics": [family], "curriculum_family": family,
        "interview_frequency": "Common", "description": description,
        "constraints": ["Write one read-only SELECT or WITH query in the selected dialect.", "The selected dialect is translated for local SQLite compatibility before judging.", "Return columns in exactly the requested order.", SCHEMA],
        "examples": [{"input": "", "output": cases[0]["expected_output"], "explanation": "The example uses one managed dataset; hidden cases change the stated edge conditions."}],
        "starter_code": STARTER, "solution": solution, "hints": list(hints),
        "expected_complexity": complexity, "public_tests": cases[:2], "hidden_tests": cases[2:],
        "sql_setup": cases[0]["setup_sql"],
    }


_M = {
"reports": ("", "INSERT INTO employees VALUES (9,'Ivy',1,1,95,'2024-05-01');", "UPDATE employees SET manager_id=NULL WHERE id=3;", "INSERT INTO employees VALUES (9,'Ivy',2,4,85,'2024-05-01');", "DELETE FROM employees WHERE id=5;", "INSERT INTO employees VALUES (9,'Ivy',4,7,90,'2024-05-01');"),
"avg": ("", "INSERT INTO employees VALUES (9,'Ivy',1,1,110,'2024-05-01');", "UPDATE employees SET salary=120 WHERE id=2;", "INSERT INTO employees VALUES (9,'Ivy',2,4,90,'2024-05-01');", "DELETE FROM employees WHERE id=8;", "UPDATE employees SET salary=60 WHERE id=7;"),
"rank": ("", "INSERT INTO employees VALUES (9,'Ivy',1,1,100,'2024-05-01');", "UPDATE employees SET salary=120 WHERE id=2;", "INSERT INTO employees VALUES (9,'Ivy',2,4,95,'2024-05-01');", "DELETE FROM employees WHERE id=5;", "UPDATE employees SET department_id=1 WHERE id=8;"),
"orders": ("", "INSERT INTO orders VALUES (10,1,50,'paid','2024-01-04');", "UPDATE orders SET amount=60 WHERE id=1;", "INSERT INTO orders VALUES (10,2,10,'paid','2024-01-05');", "DELETE FROM orders WHERE id=6;", "INSERT INTO orders VALUES (10,7,90,'paid','2024-03-03');"),
"events": ("", "INSERT INTO events VALUES (13,2,'purchase','2024-01-06');", "UPDATE events SET occurred_at='2024-01-01' WHERE id=5;", "INSERT INTO events VALUES (13,5,'activate','2024-02-03');", "DELETE FROM events WHERE id=8;", "INSERT INTO events VALUES (13,4,'activate','2024-02-02');"),
"sets": ("", "INSERT INTO skills VALUES (2,'python');", "DELETE FROM skills WHERE employee_id=4 AND skill='python';", "INSERT INTO skills VALUES (5,'sql'),(5,'python');", "INSERT INTO required_skills VALUES ('excel');", "DELETE FROM required_skills WHERE skill='python';"),
"funnel": ("", "INSERT INTO events VALUES (13,3,'activate','2024-01-06');", "INSERT INTO events VALUES (13,2,'purchase','2024-01-06');", "DELETE FROM events WHERE id=5;", "INSERT INTO events VALUES (13,5,'purchase','2024-02-04');", "DELETE FROM events WHERE id=12;"),
}

_ITEMS = [
_item(101,'Manager direct-report counts','Easy','self-join', 'For every employee, return name and direct_report_count, including employees with zero direct reports. Sort count descending, then name ascending.', 'SELECT m.name,COUNT(e.id) AS direct_report_count FROM employees m LEFT JOIN employees e ON e.manager_id=m.id GROUP BY m.id,m.name ORDER BY direct_report_count DESC,m.name', ('Start from managers, not reports.','Count a nullable report identifier.','Keep the left join for zero counts.'), 'One self join and grouped count.', _M['reports']),
_item(102,'Employee manager pairs','Easy','self-join', 'For employees with a matching manager, return employee_name and manager_name. Sort manager_name, then employee_name ascending.', 'SELECT e.name AS employee_name,m.name AS manager_name FROM employees e JOIN employees m ON m.id=e.manager_id ORDER BY manager_name,employee_name', ('Alias the two employee roles.','Match manager id to employee id.','An inner join excludes top-level staff.'), 'One self join.', _M['reports']),
_item(103,'Employees above their department average','Medium','correlated-subquery', 'Return name, department_id and salary for employees paid strictly above the average salary in their own department. Exclude employees without a department. Sort department_id, then name ascending.', 'SELECT e.name,e.department_id,e.salary FROM employees e WHERE e.department_id IS NOT NULL AND e.salary>(SELECT AVG(peer.salary) FROM employees peer WHERE peer.department_id=e.department_id) ORDER BY e.department_id,e.name', ('The average must be correlated by department.','Use a strict comparison.','Exclude the unassigned group explicitly.'), 'One correlated aggregate subquery.', _M['avg']),
_item(104,'Top two salaries per department','Medium','window-ranking', 'For employees with a department, return department_id, name, salary and salary_position for the two highest salaries in each department. Break equal salaries by name ascending before numbering. Sort department_id, salary_position.', 'WITH ranked AS (SELECT department_id,name,salary,ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC,name) AS salary_position FROM employees WHERE department_id IS NOT NULL) SELECT department_id,name,salary,salary_position FROM ranked WHERE salary_position<=2 ORDER BY department_id,salary_position', ('Number rows inside each department.','Name breaks equal salary ties.','Filter after computing the row number.'), 'Window rank plus one CTE.', _M['rank']),
_item(105,'Department dense salary ranks','Medium','window-ranking', 'For employees with a department, return department_id, name, salary and salary_rank. Equal salaries share a rank and the next distinct salary has no gap. Sort department_id, salary_rank, name.', 'SELECT department_id,name,salary,DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS salary_rank FROM employees WHERE department_id IS NOT NULL ORDER BY department_id,salary_rank,name', ('Partition the rank by department.','Do not include name inside the dense-rank order.','Use name only for final display ties.'), 'Partitioned dense ranking.', _M['rank']),
_item(106,'Department salary row numbers','Medium','window-ranking', 'For employees with a department, return department_id, name, salary and salary_row_number. Equal salaries receive different numbers ordered by name ascending. Sort department_id, salary_row_number.', 'SELECT department_id,name,salary,ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC,name) AS salary_row_number FROM employees WHERE department_id IS NOT NULL ORDER BY department_id,salary_row_number', ('This task requires distinct numbers for ties.','Put name in the window order.','Partition each department before numbering.'), 'Partitioned row numbering.', _M['rank']),
_item(107,'Running paid revenue','Medium','window-running-total', 'For paid orders, return id, ordered_at, amount and running_paid_revenue accumulated in ordered_at then id order. Sort ordered_at, then id.', 'SELECT id,ordered_at,amount,SUM(amount) OVER (ORDER BY ordered_at,id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_paid_revenue FROM orders WHERE status=\'paid\' ORDER BY ordered_at,id', ('Filter paid orders before the window runs.','Use an explicit ROWS frame.','Order ties by id.'), 'One ordered running-sum window.', _M['orders']),
_item(108,'Two-order moving paid average','Medium','window-moving-average', 'For paid orders, return id, employee_id, amount and trailing_two_average: the average of the current paid order and at most one preceding paid order for that employee by ordered_at then id. Sort employee_id, ordered_at, id.', 'SELECT id,employee_id,amount,AVG(amount) OVER (PARTITION BY employee_id ORDER BY ordered_at,id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS trailing_two_average FROM orders WHERE status=\'paid\' ORDER BY employee_id,ordered_at,id', ('Partition each employee separately.','The frame includes current and one prior row.','Pending orders are outside the sequence.'), 'Partitioned two-row window.', _M['orders']),
_item(109,'Paid-order change from previous','Medium','window-lag', 'For paid orders, return id, employee_id, amount and change_from_previous equal to amount minus that employee\'s previous paid amount by ordered_at then id. Show NULL for each first paid order. Sort employee_id, ordered_at, id.', 'SELECT id,employee_id,amount,amount-LAG(amount) OVER (PARTITION BY employee_id ORDER BY ordered_at,id) AS change_from_previous FROM orders WHERE status=\'paid\' ORDER BY employee_id,ordered_at,id', ('LAG needs an employee partition.','Subtract the prior amount from the current amount.','Do not replace first-row NULL values.'), 'Partitioned LAG window.', _M['orders']),
_item(110,'Next paid-order amount','Medium','window-lead', 'For paid orders, return id, employee_id, amount and next_paid_amount from that employee\'s next paid order by ordered_at then id. Show NULL when no later paid order exists. Sort employee_id, ordered_at, id.', 'SELECT id,employee_id,amount,LEAD(amount) OVER (PARTITION BY employee_id ORDER BY ordered_at,id) AS next_paid_amount FROM orders WHERE status=\'paid\' ORDER BY employee_id,ordered_at,id', ('LEAD looks forward in the ordered partition.','Pending orders must be filtered first.','Keep final NULL values.'), 'Partitioned LEAD window.', _M['orders']),
_item(111,'First event for each employee','Medium','event-sequencing', 'For employees with events, return employee_id, event_type and occurred_at for the first event by occurred_at then id. Sort employee_id ascending.', 'WITH ranked AS (SELECT employee_id,event_type,occurred_at,ROW_NUMBER() OVER (PARTITION BY employee_id ORDER BY occurred_at,id) AS position FROM events) SELECT employee_id,event_type,occurred_at FROM ranked WHERE position=1 ORDER BY employee_id', ('Rank events within each employee.','Use id as the same-time tie-breaker.','Filter to position one outside the CTE.'), 'Window row number and CTE.', ("", "INSERT INTO events VALUES (13,2,'purchase','2024-01-01');", "UPDATE events SET occurred_at='2024-01-01' WHERE id=5;", "INSERT INTO events VALUES (13,5,'activate','2024-02-01');", "DELETE FROM events WHERE id=1;", "INSERT INTO events VALUES (13,7,'signup','2024-02-28');")),
_item(112,'Last event for each employee','Medium','event-sequencing', 'For employees with events, return employee_id, event_type and occurred_at for the last event by occurred_at then id. Sort employee_id ascending.', 'WITH ranked AS (SELECT employee_id,event_type,occurred_at,ROW_NUMBER() OVER (PARTITION BY employee_id ORDER BY occurred_at DESC,id DESC) AS position FROM events) SELECT employee_id,event_type,occurred_at FROM ranked WHERE position=1 ORDER BY employee_id', ('Reverse both event ordering keys.','Rank inside each employee.','Select only position one.'), 'Window row number and CTE.', _M['events']),
_item(113,'Consecutive event-day islands','Hard','gaps-and-islands', 'Return employee_id, island_start, island_end and day_count for consecutive calendar-day event streaks. Multiple events on one day count once. Sort employee_id, island_start.', 'WITH days AS (SELECT DISTINCT employee_id,occurred_at AS day FROM events), marked AS (SELECT employee_id,day,date(day,\'-\'||ROW_NUMBER() OVER (PARTITION BY employee_id ORDER BY day)||\' days\') AS grp FROM days) SELECT employee_id,MIN(day) AS island_start,MAX(day) AS island_end,COUNT(*) AS day_count FROM marked GROUP BY employee_id,grp ORDER BY employee_id,island_start', ('Deduplicate days before numbering.','Subtract the row number from each date.','Group by the resulting stable island key.'), 'Deduplication, window numbering, grouped CTEs.', _M['events']),
_item(114,'Management hierarchy paths','Hard','recursive-cte', 'Return every employee name, hierarchy_depth and hierarchy_path from a top-level employee down through reports. Top-level depth is zero; join names in the path with >. Sort hierarchy_path ascending.', 'WITH RECURSIVE org(id,name,depth,path) AS (SELECT id,name,0,name FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id,e.name,org.depth+1,org.path||\'>\'||e.name FROM employees e JOIN org ON e.manager_id=org.id) SELECT name,depth AS hierarchy_depth,path AS hierarchy_path FROM org ORDER BY hierarchy_path', ('Anchor rows have no manager.','The recursive step joins reports to the prior level.','Append the child name to the existing path.'), 'Recursive traversal of the management tree.', _M['reports']),
_item(115,'Recursive event-date calendar','Hard','recursive-cte', 'Return one column named calendar_day for every calendar date from the earliest event date through the latest event date inclusive. Sort calendar_day ascending.', 'WITH RECURSIVE bounds AS (SELECT MIN(date(occurred_at)) AS first_day,MAX(date(occurred_at)) AS last_day FROM events), calendar(calendar_day,last_day) AS (SELECT first_day,last_day FROM bounds UNION ALL SELECT date(calendar_day,\'+1 day\'),last_day FROM calendar WHERE calendar_day<last_day) SELECT calendar_day FROM calendar ORDER BY calendar_day', ('Find the minimum and maximum event day first.','Carry the ending bound through recursion.','Stop after emitting the last day.'), 'Bounds CTE plus recursive date sequence.', ("", "UPDATE events SET occurred_at='2024-01-02' WHERE id=1;", "INSERT INTO events VALUES (13,7,'purchase','2024-03-06');", "DELETE FROM events WHERE id=12;", "UPDATE events SET occurred_at='2024-01-03' WHERE id IN (1,2,4);", "INSERT INTO events VALUES (13,1,'signup','2023-12-31');")),
_item(116,'Signup funnel conversion','Medium','cte-funnel', 'Return one row with signup_people, activated_people and purchased_people: distinct employees who have each event type, where activation and purchase counts are not required to be subsets in the raw data.', 'WITH signup AS (SELECT DISTINCT employee_id FROM events WHERE event_type=\'signup\'), activated AS (SELECT DISTINCT employee_id FROM events WHERE event_type=\'activate\'), purchased AS (SELECT DISTINCT employee_id FROM events WHERE event_type=\'purchase\') SELECT (SELECT COUNT(*) FROM signup) AS signup_people,(SELECT COUNT(*) FROM activated) AS activated_people,(SELECT COUNT(*) FROM purchased) AS purchased_people', ('Deduplicate each event population.','Build one CTE per funnel stage.','Return one count for each CTE.'), 'Three simple CTEs and scalar counts.', _M['funnel']),
_item(117,'Signup cohort purchase retention','Hard','cohort-retention', 'For each signup month, return signup_month, cohort_people and retained_people. A person is retained when they have a purchase event in the same or a later calendar month. Sort signup_month.', 'WITH cohorts AS (SELECT employee_id,substr(MIN(occurred_at),1,7) AS signup_month FROM events WHERE event_type=\'signup\' GROUP BY employee_id), retained AS (SELECT DISTINCT c.employee_id,c.signup_month FROM cohorts c JOIN events e ON e.employee_id=c.employee_id AND e.event_type=\'purchase\' AND substr(e.occurred_at,1,7)>=c.signup_month) SELECT c.signup_month,COUNT(*) AS cohort_people,COUNT(r.employee_id) AS retained_people FROM cohorts c LEFT JOIN retained r ON r.employee_id=c.employee_id GROUP BY c.signup_month ORDER BY c.signup_month', ('Build one signup month per employee.','Retention is same month or later.','Count the retained join identifier, not all rows.'), 'Cohort CTE plus distinct retained population.', _M['funnel']),
_item(118,'Active-or-paid employee union','Easy','set-operations', 'Return employee_id values for employees who either have an activate event or have a paid order. Remove duplicates and sort employee_id ascending.', 'SELECT employee_id FROM events WHERE event_type=\'activate\' UNION SELECT employee_id FROM orders WHERE status=\'paid\' ORDER BY employee_id', ('Each side returns one employee-id column.','UNION removes repeated employee identifiers.','Order only after combining the sets.'), 'Two-set union.', ("", "INSERT INTO events VALUES (13,3,'activate','2024-01-06');", "INSERT INTO orders VALUES (10,3,10,'paid','2024-01-06');", "DELETE FROM orders WHERE employee_id=5;", "DELETE FROM events WHERE employee_id=2 AND event_type='activate';", "INSERT INTO orders VALUES (10,6,10,'paid','2024-02-04');")),
_item(119,'Employees with both SQL and Python','Medium','set-operations', 'Return employee_id values having both a sql skill row and a python skill row. Remove duplicates and sort employee_id ascending.', 'SELECT employee_id FROM skills WHERE skill=\'sql\' INTERSECT SELECT employee_id FROM skills WHERE skill=\'python\' ORDER BY employee_id', ('Make one set for each skill.','INTERSECT keeps members of both sets.','The output has one column.'), 'Two-set intersection.', _M['sets']),
_item(120,'Signed up without purchase','Medium','set-operations', 'Return employee_id values with a signup event and no purchase event. Remove duplicates and sort employee_id ascending.', 'SELECT employee_id FROM events WHERE event_type=\'signup\' EXCEPT SELECT employee_id FROM events WHERE event_type=\'purchase\' ORDER BY employee_id', ('The left side is the signup population.','EXCEPT subtracts purchase members.','Do not use event-row counts.'), 'Two-set difference.', _M['funnel']),
_item(121,'Employees with every required skill','Hard','relational-division', 'Return id and name for employees who have every skill listed in required_skills. If required_skills is empty, every employee qualifies. Sort id ascending.', 'SELECT e.id,e.name FROM employees e WHERE NOT EXISTS (SELECT 1 FROM required_skills r WHERE NOT EXISTS (SELECT 1 FROM skills s WHERE s.employee_id=e.id AND s.skill=r.skill)) ORDER BY e.id', ('Read the requirement as no missing required skill.','Use nested NOT EXISTS.','An empty requirement set makes the outer condition true.'), 'Double NOT EXISTS relational division.', _M['sets']),
_item(122,'Employees with SQL, Python, and Excel','Hard','relational-division', 'Return id and name for employees who have all three named skills: sql, python and excel. Sort id ascending.', 'SELECT e.id,e.name FROM employees e WHERE NOT EXISTS (SELECT 1 FROM (SELECT \'sql\' AS skill UNION ALL SELECT \'python\' UNION ALL SELECT \'excel\') r WHERE NOT EXISTS (SELECT 1 FROM skills s WHERE s.employee_id=e.id AND s.skill=r.skill)) ORDER BY e.id', ('Create the three required skill rows inside the query.','Use a missing-skill test for each employee.','All three skills must be present.'), 'Inline required set and relational division.', ("", "INSERT INTO skills VALUES (1,'excel');", "DELETE FROM skills WHERE employee_id=7 AND skill='excel';", "INSERT INTO skills VALUES (4,'excel');", "INSERT INTO skills VALUES (5,'sql'),(5,'python'),(5,'excel');", "INSERT INTO skills VALUES (2,'python'),(2,'excel');")),
_item(123,'Order-status revenue pivot','Medium','conditional-aggregation', 'For each employee with at least one order, return employee_id, paid_revenue, pending_revenue and refunded_revenue. Use zero for a missing status total. Sort employee_id.', 'SELECT employee_id,COALESCE(SUM(CASE WHEN status=\'paid\' THEN amount END),0) AS paid_revenue,COALESCE(SUM(CASE WHEN status=\'pending\' THEN amount END),0) AS pending_revenue,COALESCE(SUM(CASE WHEN status=\'refunded\' THEN amount END),0) AS refunded_revenue FROM orders GROUP BY employee_id ORDER BY employee_id', ('Group once per employee.','Use one conditional sum for each status.','COALESCE turns a missing status into zero.'), 'Grouped conditional aggregation.', _M['orders']),
_item(124,'Median employee salary','Hard','median', 'Return one column named median_salary for all employee salaries. For an even employee count, return the average of the two middle salaries. Return NULL only if there are no employees.', 'WITH ordered AS (SELECT salary,ROW_NUMBER() OVER (ORDER BY salary) AS rn,COUNT(*) OVER () AS n FROM employees) SELECT AVG(salary) AS median_salary FROM ordered WHERE rn IN ((n+1)/2,(n+2)/2)', ('Number salaries in ascending order.','Also carry the total row count.','The two integer middle positions collapse for odd counts.'), 'Window numbering and median selection.', _M['avg']),
_item(125,'Duplicate employee names','Medium','data-quality', 'Return name and duplicate_count for names appearing more than once in employees. Sort duplicate_count descending, then name ascending.', 'SELECT name,COUNT(*) AS duplicate_count FROM employees GROUP BY name HAVING COUNT(*)>1 ORDER BY duplicate_count DESC,name', ('Group by the value being checked.','HAVING filters the grouped counts.','Use a strict count greater than one.'), 'Grouped duplicate detection.', ("INSERT INTO employees VALUES (9,'Ada',2,4,85,'2024-05-01');", "INSERT INTO employees VALUES (9,'Ada',2,4,85,'2024-05-01'),(10,'Ben',1,1,95,'2024-05-02');", "UPDATE employees SET name='Ada' WHERE id=2;", "UPDATE employees SET name='Solo' WHERE id=1; UPDATE employees SET name='Solo' WHERE id=2;", "DELETE FROM employees WHERE id=1;", "INSERT INTO employees VALUES (9,'Gia',2,4,85,'2024-05-01');")),
]

SQL_CURRICULUM_PART1 = _ITEMS
assert [item["id"] for item in SQL_CURRICULUM_PART1] == [f"sql-curated-{n:03d}" for n in range(101,126)]


def validate_reference_cases() -> None:
    """Replay static expected outputs; deliberately performs no work on import."""
    import sqlite3
    for item in SQL_CURRICULUM_PART1:
        for case in item["public_tests"] + item["hidden_tests"]:
            connection = sqlite3.connect(":memory:")
            try:
                connection.executescript(case["setup_sql"])
                rows = connection.execute(item["solution"]).fetchall()
                rendered = "\n".join("\t".join("NULL" if value is None else str(value) for value in row) for row in rows)
                assert rendered == case["expected_output"], item["id"]
            finally:
                connection.close()
